### PR TITLE
fix: muted chats were not marked read when marking account as read

### LINKED ISSUE #5891: Mark All As Read not working for muted chats
- Operating System: FreeBSD
- Delta Chat Version: 2.33.0
- Expected behavior: account level "mark as read" works on all chats
- Actual behavior: does not work on a muted chat

On desktop, right clicking on an account and selecting "mark all as read" isn't applying to a muted chat. Those remain with the unread badge at the chat level, but the account level doesn't show any unread messages.

Image

### PR DESCRIPTION
**Pull request by Simon-Laux**
This fixes the issue, moves maintenance burden of the method from UI to core and improves performance by removing the need to load all fresh messages to find out their chat id.

Depends on:
- core with https://github.com/chatmail/core/pull/7709
- should be merged after #5922

closes #5891

### CODE REVIEW

**Comment by WofWca** [comment]
The blockers for this MR have been resolved.

File: packages/frontend/src/components/AccountListSidebar/AccountItem.tsx [hunk 1]
```diff
@@ -330,23 +330,6 @@ export default function AccountItem({
...
-      }
-    }
-  }
-  // Add archived chats to also mark them as read
-  uniqueChatIds.add(C.DC_CHAT_ID_ARCHIVED_LINK)
-
-  for (const chatId of uniqueChatIds) {
-    await BackendRemote.rpc.marknoticedChat(accountId, chatId)
-  }
+  await BackendRemote.rpc.marknoticedAllChats(accountId)
```
Comment (ralphtheninja) [inline packages/frontend/src/components/AccountListSidebar/AccountItem.tsx:333]: Fixing a bug by removing code. Love it! <3

**Comment by WofWca** [comment]
> Error occurred in handler for 'notifications.clearAccount': TypeError: Cannot convert undefined or null to object
at Object.keys ()

I believe that happens for accounts that never received a notification on this session. We should handle `notifications[Number(accountId)]) == undefined`

File: packages/frontend/src/components/AccountListSidebar/AccountItem.tsx (hunk 1 above)
Comment (Simon-Laux) [reply packages/frontend/src/components/AccountListSidebar/AccountItem.tsx:333]: Well logic moved to core, where we have more control what it can do. :smile:

**Review by nicodh — APPROVED** [review]
Reviewed by reading & testing
