### PR TITLE
fix: remove dotenv dependency

### LINKED ISSUE #5788: released version prints `dotenv` advertisments to console
We don't want that.
I guess dotenv is used only for testing, maybe it would be easiest to exclude it on release builds.

```
[user@machine:~]$ deltachat --version
#[dotenv@17.2.3] injecting env (0) from .env -- tip: ✅ audit secrets and track compliance: https://dotenvx.com/ops
2.25.3

[user@machine:~]$ deltachat --version
[dotenv@17.2.3] injecting env (0) from .env -- tip: 🗂️ backup and recover secrets: https://dotenvx.com/ops
2.25.3

[user@machine:~]$ deltachat --version
[dotenv@17.2.3] injecting env (0) from .env -- tip: ⚙️  override existing env vars with { override: true }
2.25.3

[user@machine:~]$ deltachat --version
[dotenv@17.2.3] injecting env (0) from .env -- tip: ✅ audit secrets and track compliance: https://dotenvx.com/ops
2.25.3

[user@machine:~]$ deltachat --version
[dotenv@17.2.3] injecting env (0) from .env -- tip: ⚙️  load multiple .env files with { path: ['.env.local', '.env'] }
2.25.3

[user@machine:~]$ deltachat --version
[dotenv@17.2.3] injecting env (0) from .env -- tip: 🗂️ backup and recover secrets: https://dotenvx.com/ops
2.25.3
```

### PR DESCRIPTION
**Pull request by nicodh**
resolves #5788

Since node version 20 we can load .env files without dotenv

includes a playwright upgrade

### CODE REVIEW

File: packages/target-browser/src/config.ts [hunk 1]
```diff
@@ -2,12 +2,17 @@ import { LocalStorage } from 'node-localstorage'
...
 
 const __dirname = dirname(fileURLToPath(import.meta.url))
 
-config({ path: join(__dirname, '../') + '.env' })
+const envPath = join(__dirname, '../.env')
+
+try {
+  process.loadEnvFile?.(envPath)
+} catch (error) {
+  console.error(`Failed to load ${envPath}`, error)
```
Comment (WofWca) [inline packages/target-browser/src/config.ts:15]:
```suggestion
  // eslint-disable-next-line no-console
  console.error(`Failed to load ${envPath}`, error)
```
