### PR TITLE
Fix MessageList not updating/scrolling down on incoming message

### LINKED ISSUE #1222: Receiving message in chat but message not added to the chat area
I opened a chat with another test email, send 3 consecutive messages from the other side, in my delta chat the messages are received and shown in the chat list in the last message preview of the chat, but in the opened chat the message doesn't appear until I start typing something (and the scroll isn't moved to the end) or when changing to other chat and going back to the chat, probably related to my previous issue

### PR DESCRIPTION
**Pull request by Jikstra**
Fixes #1222

### CODE REVIEW

File: src/renderer/components/message/MessageList.js [hunk 1]
```diff
@@ -41,8 +41,10 @@ export default function MessageList ({ chat, refComposer, locationStreamingEnabl
 
   useEffect(() => {
     if (scrollToBottomIfClose === false) return
-    if (messageListRef.current.scrollHeight - messageListRef.current.scrollTop > 400) {
-      // we are close to bottom so scroll down to show the new message
+    // For whatever reason the scrollTop is ~1000 off...
```
Comment (Simon-Laux) [inline src/renderer/components/message/MessageList.js]: _For the protocol: I do not like this "we don't know what its doing lets fix it anyway somehow" approach_

**Comment by Simon-Laux** [comment]
The scrolling is not working (I only tested it with the window in the background) but the update bug is fixed.

File: src/renderer/stores/chat.js [hunk 2]
```diff
@@ -66,8 +66,7 @@ chatStore.reducers.push(({ type, payload, id }, state) => {
       messages: {
         ...state.messages,
         ...payload.messagesIncoming
-      },
-      scrollToBottomIfClose: true
```
Comment (nicodh) [inline src/renderer/stores/chat.js]: this line is needed: in my tests it only scrolls down if this is true. Why did you remove it?
