### PR TITLE
Avoid adding plain address contacts to groups

### LINKED ISSUE #5336: Can add address-contacts to encrypted group (but it rightfully fails)
- Operating System (Linux/Mac/Windows/iOS/Android): All
- Delta Chat Version: 2.6.0
- Expected behavior: Can't add address-contacts to encrypted group in the "Add Members" dialog
- Actual behavior: Can
- Steps to reproduce the problem:
  1. "New Chat"
  2. "New Group"
  3. "Add Members"
  4. Type in an email address and click on the checkbox.
  5. Finalize group creation
  6. Take a look at the list of members. You'll see that the address-contacts are not present there.
- Screenshots:
  
  Image

- Logs:

This is related to https://github.com/deltachat/deltachat-desktop/issues/5294 :

> remove "Add Contact Manually" from the "New Chat" dialog. double check, the option exist at "New Chat / New Contact", "QR Code" and "New Chat / New E-Mail / Add Recipients"

Maybe we after all need a separate "Add contact manually" button, because this whole thing with typing the address in search is weird. It's a search UX-wise, and you don't expect to "find" an address that you never added to Delta Chat there.

### PR DESCRIPTION
**Pull request by nicodh**
resolves #5336

### CODE REVIEW

File: packages/frontend/src/components/dialogs/CreateChat/index.tsx [hunk 1]
```diff
@@ -246,13 +247,20 @@ function CreateChatMain(props: CreateChatMainProps) {
...
     if (!queryStrIsValidEmail) return
 
-    const contactId = await BackendRemote.rpc.createContact(
-      accountId,
-      queryStr.trim(),
-      null
-    )
-    await createChatByContactId(accountId, contactId)
-    onClose()
+    try {
```
Comment (WofWca) [inline packages/frontend/src/components/dialogs/CreateChat/index.tsx:250]: Are these `try` wrappers unrelated or are they somehow relevant?

File: packages/frontend/src/components/dialogs/AddMember/AddMemberDialog.tsx [hunk 2]
```diff
@@ -32,6 +32,10 @@ export function AddMemberDialog({
     queryStrIsValidEmail,
     refreshContacts,
   } = useLazyLoadedContacts(listFlags, queryStr)
+
+  // compare bitwise if address flag is set
+  const allowAddManually = (listFlags & C.DC_GCL_ADDRESS) !== 0
```
Comment (WofWca) [inline packages/frontend/src/components/dialogs/AddMember/AddMemberDialog.tsx:37]: Hmmm, I'd prefer a more direct way to determine this.

File: CHANGELOG.md [hunk 3]
```diff
@@ -8,7 +8,7 @@
 ### Added
 
 ### Fixed
-
+- disable adding address contacts to groups #5336
```
Comment (WofWca) [inline CHANGELOG.md]:
```suggestion
- don't show "add contact manually" (by email address) on Chatmail accounts, because it's useless most of the time #5336
```

**Review by WofWca — APPROVED** [review]
Looks good, though I didn't test.

This also addresses https://github.com/deltachat/deltachat-desktop/pull/5358#discussion_r2242710963

File: packages/frontend/src/components/dialogs/CreateChat/index.tsx (hunk 1 above)
Comment (nicodh) [reply packages/frontend/src/components/dialogs/CreateChat/index.tsx:250]: well I came on this when testing what happens if createGroup throws an error. It turned out nothing. So I wrapped it in try catch and found this other case where a thrown error would just vanish. So yes it is unrelated

File: packages/frontend/src/components/dialogs/AddMember/AddMemberDialog.tsx (hunk 2 above)
Comment (nicodh) [reply packages/frontend/src/components/dialogs/AddMember/AddMemberDialog.tsx:37]: We could an additional parameter. I heard that there are anyway changes planned in that area so we will soon refactor here

File: CHANGELOG.md (hunk 3 above)
Comment (nicodh) [reply CHANGELOG.md]: Adapted it, but _"removed "Add contact manually" when on chatmail account"_ is already in the changed section
