### PR TITLE
fix: enable sticker replies

### LINKED ISSUE #2998: Sending a sticker as answer (with a quote) is not possible from desktop
if reply is set, but the draft is otherwise empty (no image/file/text), then the quote should be attached to the sticker and sent out.

### PR DESCRIPTION
**Pull request by nicodh**
resolves #2998

### CODE REVIEW

File: packages/frontend/src/components/composer/EmojiAndStickerPicker.tsx [hunk 1]
```diff
@@ -28,30 +29,49 @@ type Props = {
...
     const stickerPath = fileName.replace('file://', '')
-    BackendRemote.rpc.sendSticker(accountId, chatId, stickerPath).then(msgId =>
+
+    // If there's a quote, send the sticker with the quote
+    if (draftQuote && draftQuote.kind === 'WithMessage') {
+      await sendMessage(accountId, chatId, {
+        file: stickerPath,
+        viewtype: 'Sticker',
+        quotedMessageId: draftQuote.messageId,
+      })
```
Comment (WofWca) [inline packages/frontend/src/components/composer/EmojiAndStickerPicker.tsx]: Do you have a justification why it's OK to skip `msg.force_sticker();`?
Otherwise we need to add the `quote_message_id` param to the `send_sticker` function.

https://github.com/chatmail/core/blob/8b58b16cb528e29a7f69f1337a3889333fa413c7/deltachat-jsonrpc/src/api.rs#L2362-L2378

Comment (link2xt) [reply packages/frontend/src/components/composer/EmojiAndStickerPicker.tsx]: There is a logic that may turn Viewtype::Sticker into non-sticker if it looks like a screenshot:
https://github.com/chatmail/core/blob/d069e75cd8cbd2ac12d3817429fa584174e86175/src/message.rs#L2324-L2330

IIRC was introduced for the case when an image was dragged from gallery into the chat on iOS, resulting in sending screenshots as stickers.

Comment (link2xt) [reply packages/frontend/src/components/composer/EmojiAndStickerPicker.tsx]: After some discussion with @r10s, plan is to remove sticker heuristics and `force_sticker()` in the core, then fix the problems in each UI that accidentally sends screenshots as stickers: https://github.com/chatmail/core/pull/8162

Comment (nicodh) [reply packages/frontend/src/components/composer/EmojiAndStickerPicker.tsx]: So for now we can leave this PR as it is. Although if you have images as sticker they will end up to be transformed by core to and sent as normal image message. After core is updated we could adapt what is needed

Comment (nicodh) [reply packages/frontend/src/components/composer/EmojiAndStickerPicker.tsx]: I tested this with current core and the viewType Sticker in the sent message is preserved now so no adaptions needed

Comment (WofWca) [reply packages/frontend/src/components/composer/EmojiAndStickerPicker.tsx]: Kind of looks like `send_sticker` is not needed at all then.

File: packages/frontend/src/components/composer/EmojiAndStickerPicker.tsx [hunk 2]
```diff
@@ -257,6 +292,8 @@ export const EmojiAndStickerPicker = forwardRef<
           chatId={chatId}
           stickers={stickers}
           setShowEmojiPicker={setShowEmojiPicker}
+          draftQuote={draftQuote}
+          removeQuote={removeQuote}
```
Comment (WofWca) [inline packages/frontend/src/components/composer/EmojiAndStickerPicker.tsx]: Feels like we shouldn't be passing such functions so deeply to `StickerPicker`. Instead handle "sticker click" somewhere higher.

File: packages/frontend/src/components/composer/EmojiAndStickerPicker.tsx [hunk 3]
```diff
@@ -28,30 +29,49 @@ type Props = {
   stickerPackImages: string[]
   chatId: number
   setShowEmojiPicker: (enabled: boolean) => void
+  draftQuote?: DraftObject['quote']
+  removeQuote?: () => void
```
Comment (WofWca) [inline packages/frontend/src/components/composer/EmojiAndStickerPicker.tsx]:
```suggestion
  draftQuote: DraftObject['quote']
  removeQuote: () => void
```

I'd say these shouldn't be optional.
It still compiles then.

**Review by WofWca — APPROVED** [review]
Works alright. I though about race conditions like https://github.com/deltachat/deltachat-desktop/issues/3738 https://github.com/chatmail/issue-stargate/issues/13. I couldn't come up with anything too bad. The quote might linger around until the message gets sent, but that alone doesn't enable the "double send" bug.

File: packages/frontend/src/components/composer/EmojiAndStickerPicker.tsx (hunk 2 above)
Comment (nicodh) [reply packages/frontend/src/components/composer/EmojiAndStickerPicker.tsx]: I agree and changed it to be handled inside composer

File: packages/frontend/src/components/composer/EmojiAndStickerPicker.tsx (hunk 3 above)
Comment (nicodh) [reply packages/frontend/src/components/composer/EmojiAndStickerPicker.tsx]: Is obsolete with last commit

**Review by WofWca — APPROVED** [review]
Tested again, still works. The code looks better.
