### PR TITLE
Hide add contact manually if on chatmail

### LINKED ISSUE #5336: Can add address-contacts to encrypted group (but it rightfully fails)
- Operating System (Linux/Mac/Windows/iOS/Android): All
- Delta Chat Version: 2.6.0
- Expected behavior: Can't add address-contacts to encrypted group in the "Add Members" dialog
- Actual behavior: Can
- Steps to reproduce the problem:
  1. "New Chat"
  2. "New Group"
  3. "Add Members"
  4. Type in an email address and click on the checkbox.
  5. Finalize group creation
  6. Take a look at the list of members. You'll see that the address-contacts are not present there.
- Screenshots:
  
  Image

- Logs:

This is related to https://github.com/deltachat/deltachat-desktop/issues/5294 :

> remove "Add Contact Manually" from the "New Chat" dialog. double check, the option exist at "New Chat / New Contact", "QR Code" and "New Chat / New E-Mail / Add Recipients"

Maybe we after all need a separate "Add contact manually" button, because this whole thing with typing the address in search is weird. It's a search UX-wise, and you don't expect to "find" an address that you never added to Delta Chat there.

### PR DESCRIPTION
**Pull request by nicodh**
This is the first step to resolve _"remove "Add Contact Manually"_ in #5294

"Add contact manually" should never be shown when on a Chatmail account since it is not possible to add a contact just by email.

It does only partial resolve #5336 though, since on non chatmail accounts it is still possible to add contacts manually to Groups. That willl be addressed in another PR

### CODE REVIEW

File: packages/frontend/src/components/helpers/PseudoListItem.tsx [hunk 1]
```diff
@@ -117,13 +117,13 @@ export const PseudoListItemAddContact = ({
   const settingsStore = useSettingsStore()[0]
   const isChatmail = settingsStore?.settings.is_chatmail === '1'
 
+  if (isChatmail) return null
```
Comment (WofWca) [inline packages/frontend/src/components/helpers/PseudoListItem.tsx:120]: This approach is IMO not the best semantically, might cause bugs in the future. Namely, `contactsAndExtraItems.length` is calculated to account for the presence of this element, but it's not present.

https://github.com/deltachat/deltachat-desktop/blob/a36f56ff9c7600ef380f90db33dcae54cb48f08b/packages/frontend/src/components/dialogs/CreateChat/index.tsx#L345

https://github.com/deltachat/deltachat-desktop/blob/a36f56ff9c7600ef380f90db33dcae54cb48f08b/packages/frontend/src/components/dialogs/CreateChat/index.tsx#L212-L226

It's better to modify `contactsAndExtraItems`, in case of the `CreateChat` component. For other components where `PseudoListItemAddContact` is used, it's probably the same.

**Review by WofWca — APPROVED** [review]
If the plan is to completely remove the possibility of adding address-contacts on Chatmail accounts, including `echo@nine.testrun.org`, `admin@nine.testrun.org` ([`passthrough_recipients`](https://github.com/chatmail/relay/blob/d880937d448a1fcdd94006659e54b144d0b912f6/chatmaild/src/chatmaild/ini/chatmail.ini.f#L41-L46)), and for the possible whitelisted senders (`passthrough_senders`), then this does the job (apart from the "add members" part that you mentioned in the MR description).

Related:
- https://github.com/deltachat/deltachat-android/issues/3163
- https://github.com/deltachat/deltachat-android/pull/3166
- https://github.com/deltachat/deltachat-android/pull/3064
- https://github.com/deltachat/deltachat-desktop/issues/3833

File: packages/frontend/src/components/helpers/PseudoListItem.tsx (hunk 1 above)
Comment (nicodh) [reply packages/frontend/src/components/helpers/PseudoListItem.tsx:120]: Yes I will address this in the follow up (that's why the branch is named hide-add-manually-step1

But this change makes sure the PseudoListItemAddContact is never shown on chatmail accounts.

We need to pass a parameter to the AddMemberDialog to decide wether the add contact manually should be shown etc.

Comment (WofWca) [reply packages/frontend/src/components/helpers/PseudoListItem.tsx:120]: > But this change makes sure the PseudoListItemAddContact is never shown on chatmail accounts.

Yes, I think keeping the condition in two places, inside and outside, is ok.
