### PR TITLE
fix emailadress parsing bug in message

### LINKED ISSUE #613: mailaddresses in messages cause doubling of message text
current master: if you send a message with an email address, say: "email@email.org blaaaaa" then the rendering of the message on the sending side will be "email@email.org blaaaaa blaaaa".   Android shows the message correctly so this is quite definitively a desktop processing/rendering problem.

### PR DESCRIPTION
**Pull request by Simon-Laux**
fixes #613

### CODE REVIEW

File: src/renderer/components/conversations/Linkify.js [hunk 1]
```diff
@@ -37,7 +37,7 @@ class Linkify extends React.Component {
           </a>
         )
       } else {
-        results.push(renderNonLink({ text, key: count++ }))
+        results.push(renderNonLink({ text: originalText, key: count++ }))
```
Comment (ralphtheninja) [inline src/renderer/components/conversations/Linkify.js]: :+1: 

@Simon-Laux It's fine to not review everything. Good call.
