### PR TITLE
Select chat after forwarding

### LINKED ISSUE #3834: chat does not scroll down after forwarding
steps to reproduce:
- forward message to different chat (that is not saved messages, because saved messages is intentionally not selected)
- observer that you need to scroll down to see the message

### PR DESCRIPTION
**Pull request by nicodh**
fixes #3834

### CODE REVIEW

File: src/renderer/components/dialogs/ForwardMessage/index.tsx [hunk 1]
```diff
@@ -45,15 +45,14 @@ export default function ForwardMessage(props: Props) {
     const chat = await BackendRemote.rpc.getFullChatById(accountId, chatId)
     onClose()
     if (!chat.isSelfTalk) {
-      selectChat(accountId, chat.id)
```
Comment (Simon-Laux) [inline src/renderer/components/dialogs/ForwardMessage/index.tsx:48]: this is there because then you see the chat you are going to forward to, to prevent user mistakes.

Comment (nicodh) [reply src/renderer/components/dialogs/ForwardMessage/index.tsx:48]: Ok - that should be worth a line of an explaining comment in the code :-)

So I have to find why the already opened chat is not scrolling down I guess

Comment (Simon-Laux) [reply src/renderer/components/dialogs/ForwardMessage/index.tsx:48]: maybe calling select chat again could already work. or whatever happens when you click again on the chat in the chat-list if you have already selected the chat,

**Review by Simon-Laux — APPROVED** [review]

**Review by Simon-Laux — APPROVED** [review]
Code LGTM, but I didn't test it
