### PR TITLE
Use worker for processing qr images

### LINKED ISSUE #4639: On PinePhone, scanning a qr code from an image will hang for a really long time like the app crashed
On PinePhone, scanning a qr code from an image will hang for a really long time like the app crashed. The problem seems to be that whatever the scanner does is really slow on this device, and there is zero indicator what's going on and the window also gets stuck when switching between portrait and landscape. Ideally, the window should remain responsive and show some scanning indicator that includes some sort of progress bar.

- Operating System (Linux/Mac/Windows/iOS/Android): Linux ARM64
- Delta Chat Version: desktop 1.50.1 (flathub) core 1.152.1
- Expected behavior: Progress indicator is shown and user understands what's going on
- Actual behavior: Window plays dead
- Steps to reproduce the problem: 1. Use a very slow device. 2. Get a QR code image, preferably blurry and challenging. 3. Scan by opening the image from a file, 5. After file choice was confirmed in the file open dialog, watch what happens right after
- Screenshots:
- Logs:

### PR DESCRIPTION
**Pull request by nicodh**
Resolves #4639

- show the spinner while processing imported qr code images or clipboard
- enable to cancel the processing if it takes too long
- call QrCode.handlePasteFromClipboard from parent component
- use second worker for clipBoard processing to avoid race conditions

### CODE REVIEW

File: packages/frontend/src/components/QrReader/index.tsx [hunk 1]
```diff
@@ -13,360 +15,475 @@ import useTranslationFunction from '../../hooks/useTranslationFunction'
...
+    useEffect(() => {
+      worker = new QrWorker() as Worker
+      workerClipBoard = new QrWorker() as Worker
+      return () => {
+        // terminate worker if component is unmounted,
+        // otherwise we might get a delayed error message
+        // if scan fails, even after closing the QR dialog
+        worker.terminate()
+        workerClipBoard.terminate()
       }
```
Comment (WofWca) [inline packages/frontend/src/components/QrReader/index.tsx:82]: If we go this route, then we should have the workers scoped to the component instance, and not globally.

**Review by WofWca — COMMENTED** [review]
This should be better.

Though, to note, `fileToBase64` is still performed on the main thread.

File: packages/frontend/src/components/QrReader/index.tsx [hunk 2]
```diff
@@ -13,360 +15,475 @@ import useTranslationFunction from '../../hooks/useTranslationFunction'
...
+          if (!data) {
+            throw new Error('no data in clipboard')
+          }
+          // trim whitespaces because user might copy them by accident when sending over other messengers
+          // see https://github.com/deltachat/deltachat-desktop/issues/4161#issuecomment-2390428338
+          onScanSuccess(data.trim())
         }
-      } catch (error: any) {
+      } catch (error) {
+        setProcessingFile(false)
```
[the remark this answers is not in the document]
Comment (nicodh) [reply packages/frontend/src/components/QrReader/index.tsx]: > setProcessingFile usage seems more convoluted than it has to be. Is there no simpler way?

setProcessingFile is set to true in handleFileInputChange or handlePasteFromClipboard to show the user that "something" is processing. It is either reset to false in processQrCodeWithWorker if that is reached, otherwise set to false in the "else" condition


> there is a bug where after clicking "paste" with plain text in your clipboard, processingFile never gets reset to false

is fixed

**Comment by nicodh** [comment]
Code check fails with:

`/home/runner/work/deltachat-desktop/deltachat-desktop/packages/frontend/src/components/dialogs/QrCode.tsx
Error:   22:10  error  'runtime' is defined but never used. Allowed unused vars must match /^_/u  @typescript-eslint/no-unused-vars`

which is wrong since runtime IS used in line  85

File: packages/frontend/src/components/QrReader/index.tsx [hunk 3]
```diff
@@ -34,352 +41,482 @@ type Props = {
...
+    const inputRef = useRef<HTMLInputElement>(null)
+
+    const [ready, setReady] = useState(false)
+    const [cameraAccessError, setCameraAccessError] = useState(false)
+    const [videoDevices, setVideoDevices] = useState<MediaDeviceInfo[]>([])
+    const [deviceId, setDeviceId] = useState<string | undefined>(undefined)
+    const [processingFile, setProcessingFile] = useState(false)
+
+    const worker = useRef<Worker>(new QrWorker() as Worker)
+    const workerClipBoard = useRef<Worker>(new QrWorker() as Worker)
```
Comment (WofWca) [inline packages/frontend/src/components/QrReader/index.tsx:73]: This unconditionally instantiates a new worker on every render, resulting in a memory leak.

Maybe see https://react.dev/reference/react/useRef#avoiding-recreating-the-ref-contents on how to resolve.

**Review by WofWca — CHANGES_REQUESTED** [review]
Aside from the comment, this seems to work OK now.

**Comment by WofWca** [comment]
And about the CI error: it's weird, not reproducible locally. Let's ignore, and resolve separately if it reappears on main.

**Review by WofWca — APPROVED** [review]
I have confirmed that the memory leak is gone.
And this seems to work alright.
