### PR TITLE
Check text exists before accessing it

### LINKED ISSUE #4337: 1.48.0 crashes sometimes when i try to quote-reply
image

### PR DESCRIPTION
**Pull request by nicodh**
resolves #4337

### CODE REVIEW

File: packages/frontend/src/components/message/Message.tsx [hunk 1]
```diff
@@ -792,15 +792,18 @@ export const Quote = ({
...
-          <div className='quoted-text'>
-            <MessageBody
-              text={
-                quote.text.slice(0, 3000 /* limit quoted message size */) || ''
-              }
-              disableJumbomoji
-              nonInteractiveContent
-            />
-          </div>
+          {hasMessage && quote.text && (
```
Comment (WofWca) [inline packages/frontend/src/components/message/Message.tsx:795]: Doesn't this hide the quote when `quote.kind === 'JustText'`? Because `hasMessage` is defined as `quote.kind === 'WithMessage'`.

And I think we need a comment for the `quote.text &&` check, at least link the issue.

Comment (nicodh) [reply packages/frontend/src/components/message/Message.tsx]: So now I check only for the text property to exist.

> And I think we need a comment for the quote.text && check, at least link the issue

I think it is self explaining to check for the text property to exist before calling "slice" on it.

Comment (WofWca) [reply packages/frontend/src/components/message/Message.tsx]: Well, the thing is that the types say that it always exists.

File: packages/frontend/src/components/message/Message.tsx [hunk 2]
```diff
@@ -792,15 +792,18 @@ export const Quote = ({
...
-          <div className='quoted-text'>
-            <MessageBody
-              text={
-                quote.text.slice(0, 3000 /* limit quoted message size */) || ''
-              }
-              disableJumbomoji
-              nonInteractiveContent
-            />
-          </div>
+          {quote.text && (
```
Comment (WofWca) [inline packages/frontend/src/components/message/Message.tsx:795]:
```suggestion
          {/* `quote.text` might be `undefined` due to
          https://github.com/deltachat/deltachat-desktop/issues/4337#issuecomment-2473521298 */}
          {quote.text && (
```

**Review by WofWca — APPROVED** [review]
