### PR TITLE
Hide delete for all if unencrypted

### LINKED ISSUE #5316: Non-functional "Delete for everyone" button in email message
- Delta Chat version: ~~Current main~~ key-contacts branch
- Expected behavior: The "Delete for Everyone" button is hidden in unencrypted-email-chats
- Actual behavior: The "Delete for Everyone" button is shown in unencrypted-email-chats, but an error is shown when you click it
- Steps to reproduce the problem:
  - Send a message into an unencrypted chat
  - Right-click it and click "Delete"
  - Click "Delete for Everyone"

### PR DESCRIPTION
**Pull request by nicodh**
#skip-changelog

resolves #5316

### CODE REVIEW

File: packages/frontend/src/components/dialogs/ConfirmDeleteMessage.tsx [hunk 1]
```diff
@@ -30,7 +30,8 @@ export default function ConfirmDeleteMessageDialog(props: Props) {
     msg.sender.id === C.DC_CONTACT_ID_SELF &&
     !msg.isInfo &&
     chat.canSend &&
-    !chat.isSelfTalk
+    !chat.isSelfTalk &&
+    chat.isEncrypted
```
Comment (WofWca) [inline packages/frontend/src/components/dialogs/ConfirmDeleteMessage.tsx:34]: A comment would be nice.

**Review by WofWca — APPROVED** [review]
