### PR TITLE
fix window placement on first start

### LINKED ISSUE #1711: Welcome To DC screen gets overlapped with vertical Windows taskbar
- Operating System: remote Win 8.1, RDP connection
- Delta Chat Version: 1.3.4 - release on the official site
- Expected behavior: first ever windows to be opened about center of desktop or about mouse cursor position - but definitely should be wholelly visible
- Actual behavior: partially hidden beneath taskbar

dc_134_rdp-win81-first_run

During struggling with #1597 i explicitly purged all the files DC was creating in AppData, both local and roaming ones. I do not think that should matter anyway, but jsut for the record

### PR DESCRIPTION
**Pull request by Simon-Laux**
fixes #1711

### CODE REVIEW

File: src/main/application-constants.ts [hunk 1]
```diff
@@ -8,17 +9,24 @@ export function appIcon() {
...
-  let defaultWidth = 500
+  let defaultWidth = 1000
   if (process.env.NODE_ENV === 'test') {
     targetFile = 'test.html'
     defaultWidth = 1100
   }
+  const {height:screenHeight, width:screenWidth } = screen.getPrimaryDisplay().workAreaSize
   const headerHeight = 38
-  const messageHeight = 100
+  const defaultHeigth = Math.min(700 + headerHeight, screenHeight)
```
Comment (Jikstra) [inline src/main/application-constants.ts:19]: heigth or height? :D
