### PR TITLE
fix: add transport for DCLOGIN

### LINKED ISSUE #5844: scanning DCACCOUNT:/DCLOGIN: should behave same and create a new transport
instead of creating a new profile, one should always being asked whether to add a transport.

for DCACCOUNT:, this is already the case, however, we should do the same for DCLOGIN

- one can argue that DCLOGIN: is a bit different, however, these QR codes are pretty rare, and we do not want to have special paths for them, that introduce bugs and maintainance effort

- from the view of the user, these codes are pretty much the same

- passing DCLOGIN to addTransportFromQr() is idempotent - accidental multiple scanning does not do harm

- less can go wrong - if ppl play around, adding a transport is less harmful than a new profile where they do not know how to switch, send from different ones etc.

counterpart of https://github.com/deltachat/deltachat-ios/issues/2946

### PR DESCRIPTION
**Pull request by nicodh**
resolves #5844

### CODE REVIEW

File: packages/frontend/src/components/dialogs/Transports/index.tsx [hunk 1]
```diff
@@ -96,9 +96,9 @@ export default function TransportsDialog(
     openDialog(BasicQrScanner, {
       onSuccess: async (result: string) => {
         const { qr } = await processQr(accountId, result)
-        if (qr.kind === 'account') {
+        if (qr.kind === 'account' || qr.kind === 'login') {
           const confirmed = await addTransportConfirmationDialog(
-            qr.domain,
+            qr.kind === 'account' ? qr.domain : qr.address,
```
Comment (WofWca) [inline packages/frontend/src/components/dialogs/Transports/index.tsx:101]: This parameter is still named `domain`. It needs to be renamed.

https://github.com/deltachat/deltachat-desktop/blob/c63297d5bf1cc0007ad657ae05ac9661fbb9ccae/packages/frontend/src/components/dialogs/Transports/index.tsx#L22

File: packages/frontend/src/components/dialogs/Transports/index.tsx
Comment (WofWca) [inline packages/frontend/src/components/dialogs/Transports/index.tsx:109]: Is Core actually supposed to be able to handle `login` QRs? `addTransportFromQr` docs state

>      * Adds a new email account as a transport
>      * using the server encoded in the QR code.

Edit: OK, it does. Its docs need to be updated.

https://github.com/chatmail/core/blob/f7ae2abe5262b51d7f4633a5dc1237931a07169e/src/configure.rs#L161-L172

File: packages/frontend/src/hooks/useProcessQr.ts [hunk 2]
```diff
@@ -316,35 +319,6 @@ export default function useProcessQR() {
...
-          const userConfirmed = await openConfirmationDialog({
-            message: tx('qrlogin_ask_login_another', qr.address),
-            confirmLabel: tx('login_title'),
-          })
-
-          if (!userConfirmed) {
-            return callback?.()
-          }
-
-          const new_accountId = await addAndSelectAccount()
```
Comment (WofWca) [inline packages/frontend/src/hooks/useProcessQr.ts:339]: Apparently this was the last place where `addAndSelectAccount` was used. I think this means that we should add a comment that says that `addAndSelectAccount` of `ScreenContext` is unused so it can be removed.

https://github.com/deltachat/deltachat-desktop/blob/a5c02433976909fe01a64f3049c96d0d101ae9d8/packages/frontend/src/contexts/ScreenContext.tsx#L9-L10

File: packages/frontend/src/hooks/useProcessQr.ts [hunk 3]
```diff
@@ -294,10 +297,10 @@ export default function useProcessQR() {
        * 2. unconfigured account: set instant onboarding chatmail instance
```
Comment (WofWca) [inline packages/frontend/src/hooks/useProcessQr.ts]: The comment needs to be updated I think. This part is only supposed to apply to `DCACCOUNT`, but now it seems that it applies to both.

**Comment by r10s** [comment]
> If we urgently need it for the release

no, a release is totally fine without this PR. 

DCLOGIN is a super-rare thing, scanning that from main scanner even more

(this is also the reason, we really want to have the exact same code paths as DCACCOUNT. since years that DCLOGIN always gets far more resources than it deserves :)

File: packages/frontend/src/hooks/useProcessQr.ts [hunk 4]
```diff
@@ -284,20 +282,24 @@ export default function useProcessQR() {
...
+       * see https://github.com/deltachat/interface/blob/main/uri-schemes.md#DCLOGIN
        *
-       * contains the url to a chatmail instance which will be used in the
-       * instant onboarding process initiated by this QR code scan
        *
        * Scenarios depending on the account status:
-       * 1. configured account: Ask the user if they want to create a new profile on the given chatmail instance
-       * 2. unconfigured account: set instant onboarding chatmail instance
+       * 1. configured account: Ask the user if they want to add a new relay to the current profile
+       * 2. unconfigured account: set instant onboarding instance
```
Comment (WofWca) [inline packages/frontend/src/hooks/useProcessQr.ts:296]:
```suggestion
       * 2. unconfigured account: set instant onboarding chatmail instance
```

What's the reason for removing "Chatmail"? Can it be something other than Chatmail?

Comment (adbenitez) [reply packages/frontend/src/hooks/useProcessQr.ts:296]: dclogin is even mainly useful for non-chatmail instances, for chatmail you will use dcaccount

Comment (WofWca) [reply packages/frontend/src/hooks/useProcessQr.ts:296]: Oh, right. I thought that this is about `dcaccount`.
