### PR TITLE
fix: do not cover video controls

### LINKED ISSUE #5209: video controls obstructed by message metatdata (time stamp and status)
When watching a video, fullscreen mode cannot be activated, and the video buttons are obscured by the time stamp and encryption indicator.

macOS 15.5
DC-Desktop 1.59.1 (Tauri)

Image

### PR DESCRIPTION
**Pull request by nicodh**
Resolves #5209

Before:

image

After

image

### CODE REVIEW

File: packages/frontend/src/components/attachment/messageAttachment.tsx [hunk 1]
```diff
@@ -172,12 +172,9 @@ export default function Attachment({
...
     return (
-      <div
-        className={classNames(
-          'message-attachment-media',
-          withCaption ? 'content-below' : null
-        )}
-      >
+      // content-below is always needed even if there is no text,
+      // because videos controls should not be overlapped by meta data
+      <div className={classNames('message-attachment-media', 'content-below')}>
```
Comment (WofWca) [inline packages/frontend/src/components/attachment/messageAttachment.tsx]: Maybe it'd be simpler to adjust the CSS selector instead, by adding `.video-only` to it.

Comment (nicodh) [reply packages/frontend/src/components/attachment/messageAttachment.tsx]: What do you mean?  .video-only is used to adapt the whole message bubble background color.

Comment (WofWca) [reply packages/frontend/src/components/attachment/messageAttachment.tsx]: Yes, I understand. I mean we shouldn't apply the "contentbelow" class, and instead use the  "video only" class in CSS
