### PR TITLE
fix hard to alter text in the middle of "Video chat instance" input field

### LINKED ISSUE #2016: hard to alter text in the middle of "Video chat instance" input field
assume, "Settings / Video chat instance" is not empty and you want to enter sth. in between, say change the domain or a parameter.

if you put the cursor somewhere in the middle of the "Settings / Video chat instance" input field and enter a character, the cursor moves to the end. this makes it very hard to alter the string.

### PR DESCRIPTION
**Pull request by Simon-Laux**
fix #2016

### CODE REVIEW

File: src/renderer/components/dialogs/Settings.tsx [hunk 1]
```diff
@@ -57,6 +57,50 @@ export function SettingsSelector(props: any) {
   )
 }
 
+function DeltaInput({
```
Comment (Jikstra) [inline src/renderer/components/dialogs/Settings.tsx:60]: Hmm we already have a component called DeltaInput in LoginStyles. Can you either fuse them or give it nother name?
