### PR TITLE
fix: no leave group for contact requests

### LINKED ISSUE #5678: Don't show a 'Leave' button in contact request groups
- Expected behavior: There is no 'Leave' button in contact request groups
- Actual behavior: There is a 'Leave' button, but it doesn't do anything when clicked
- Steps to reproduce the problem:
  - Get a contact request group
  - Right-click on it, or click on the three-vertical-dots menu

Closed core PR that would have made it possible to leave contact request groups, for reference: https://github.com/chatmail/core/pull/7007

### PR DESCRIPTION
**Pull request by nicodh**
resolves #5678

### CODE REVIEW

File: packages/frontend/src/components/chat/ChatListContextMenu.tsx [hunk 1]
```diff
@@ -326,7 +326,8 @@ export function useChatListContextMenu(): {
         singleChat &&
```
Comment (Simon-Laux) [inline packages/frontend/src/components/chat/ChatListContextMenu.tsx:326]: I just noticed that this var naming "singleChat" is a bit confusing (too similar to the `ChatType: "Single"`), not related to the pr though.

**Review by Simon-Laux — APPROVED** [review]
