### PR TITLE
Fix keyboard zoom shortcuts

### LINKED ISSUE #5908: Zoom shortcuts fail in Fullscreen view
Pressing Ctrl/Meta with + does not zoom into the image but zooms only the buttons in full screen view.

And pressing Ctrl/Meta with - on a german keyboard layout opens the Shortcut help page, since the evt.code equals Slash not -

The latter happens in any view not only in FullScreen dialogs

### PR DESCRIPTION
**Pull request by nicodh**
resolves #5908

- another try to solve the evt.key vs evt.code problem on non-standard keyboard layouts
- use own zoom shortcuts handler in FullScreen views since the built-in electron zoom handler fails

### CODE REVIEW

File: packages/frontend/src/hooks/useZoomKeyboardShortcuts.ts [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+  const zoomOutRef = useRef<(() => void) | null>(null) as React.RefObject<
+    (() => void) | null
+  >
+  const zoomResetRef = useRef<(() => void) | null>(null) as React.RefObject<
+    (() => void) | null
+  >
+
+  useEffect(() => {
+    const handleKeyDown = (ev: KeyboardEvent) => {
+      if (ev.ctrlKey || ev.metaKey) {
```
Comment (WofWca) [inline packages/frontend/src/hooks/useZoomKeyboardShortcuts.ts]:
```suggestion
      if ((ev.ctrlKey || ev.metaKey) && !ev.altKey) {
```

But I did not include `&& !ev.shiftKey` because IDK maybe some layouts need Shift to get these `key`s.

File: packages/frontend/src/hooks/useZoomKeyboardShortcuts.ts [hunk 2]
```diff
@@ -0,0 +1,47 @@
+import { useEffect, useRef } from 'react'
+
+import type React from 'react'
+
+/**
+ * Hook to handle Ctrl+Plus (with fallback to 0), Ctrl+Minus,
+ * and Ctrl+0 keyboard shortcuts for zooming.
+ * Returns refs to connect to react-zoom-pan-pinch's TransformWrapper utils.
+ */
```
Comment (WofWca) [inline packages/frontend/src/hooks/useZoomKeyboardShortcuts.ts:12]:
```suggestion
 * Captures and `preventDefault()`s the respective shortcuts,
 * primarily because the same shortcuts are used
 * to change the zoom level of the entire app.
 */
```

**Review by WofWca — APPROVED** [review]
Regarding the "zoom shortcuts" part of this MR:
looks alright and works, at least for me. The feature itself makes sense. The scope where this event catching is taking place is limited, so even if it's buggy, it should not affect much.

Regarding another rewrite of the shortcut handling code: I do not hope that it's going to be bug-free (and the code doesn't look like it either), but seems to work for me. All shortcuts are working, and bugs like https://github.com/deltachat/deltachat-desktop/issues/5779 or https://github.com/deltachat/deltachat-desktop/issues/5682 did not get re-introduced. I did not test DVORAK layout though. So let's just roll with it.

File: packages/frontend/src/hooks/useZoomKeyboardShortcuts.ts (hunk 1 above)
Comment (nicodh) [reply packages/frontend/src/hooks/useZoomKeyboardShortcuts.ts]: I don't understand this suggestion and the comment? How is this related to Shift and why might it be needed?

Comment (WofWca) [reply packages/frontend/src/hooks/useZoomKeyboardShortcuts.ts]: You don't want to execute the shortcut when Alt is pressed. The same would go for Shift, but shift might be necessary on some layouts to get the required character, `key`, e.g. you'd actually have to press `Ctrl + Shift + =` to get a `plus`. For that reason you are handling both: `ev.key === '+' || ev.key === '='`. But maybe on some layouts this is the same for `Shift`.

Comment (nicodh) [reply packages/frontend/src/hooks/useZoomKeyboardShortcuts.ts]: Yes Shift might be (and is) needed. On german keyboard layout the "=" needs Shift.
