### PR TITLE
Sort chat list on update

### LINKED ISSUE #831: New group not showing up directy. It's there after restart.
- Platform (linux/mac/windows): linux
- Delta Chat Desktop Version: chatlist-refactoring branch
- Expected behavior: group is added
- Actual behavior: group is not shown until application has been restarted
- Steps to reproduce the problem: invite someone to a group and send a message to it
- Screenshots:
- Logs:

### PR DESCRIPTION
**Pull request by nicodh**
Update chat list when chat changes
Resolves #831

The chat list gets updated now on every DC_EVENT_CHAT_MODIFIED event.
Maybe we should test and check for more events which might not be handled...

### CODE REVIEW

File: src/renderer/stores/chatList.js [hunk 1]
```diff
@@ -11,15 +11,19 @@ const chatListStore = new Store(defaultState)
 // value for text1Meaning
 const DC_TEXT1_DRAFT = 1
 
+function sortChatList (first, second) {
+  return first.summary.timestamp > second.summary.timestamp ? -1 : 1
```
Comment (Jikstra) [inline src/renderer/stores/chatList.js]: I think that sorting the chatlist isn't needed, instead we should have another array which just holds the chatIds in the correct order. This we can just refetch with one call. But I will try to implement that on top of this, first lets get this bug fixed.

**Comment by ralphtheninja** [comment]
A general nit pick: Please try to remember to clean up branches after merge.
