### PR TITLE
fix missing `maps.xdc` in flatpak build

### LINKED ISSUE #4245: Nothing happens when clicking on the map icon (flathub)
- Operating System: Linux
- Delta Chat Version: 1.46.8 (git: flathub)
- Expected behavior: When clicking on the map icon in the upper right corner, a map for location sharing opens.
- Actual behavior: When clicking on the map icon in the upper right corner, nothing happens.
- Logs:

image

```
2024-10-18T20:39:58.605Z	main/index            	INFO	""	"Deltachat Version 1.46.8 flathub 1727722460000"
2024-10-18T20:39:59.103Z	main/index            	INFO	""	"cwd /home/user/.var/app/chat.delta.desktop/config/DeltaChat/accounts"
2024-10-18T20:39:59.113Z	main/deltachat        	INFO	""	"using deltachat-rpc-server at"	{"serverPath":"/app/delta/resources/app/node_modules/@deltachat/stdio-rpc-server-linux-x64/deltachat-rpc-server"}

2024-10-23T13:06:11.223Z	main/state            	INFO	""	"Saving state to /home/user/.var/app/chat.delta.desktop/config/DeltaChat/config.json"
2024-10-23T13:06:12.089Z	main/menu             	INFO	""	"rebuilding menu with locale en"
2024-10-23T13:06:12.235Z	renderer              	ERROR	"\nfile:///app/delta/resources/app/src/renderer/App.tsx:109:10"	"Unhandled Rejection:"	{"isTrusted":true}	{"stack":"Error: Error invoking remote method 'open-maps-webxdc': [object Object]\n    at IpcRenderer.invoke (node:electron/js2c/sandbox_bundle:2:49458)","message":"Error invoking remote method 'open-maps-webxdc': [object Object]"}
...

### PR DESCRIPTION
**Pull request by Simon-Laux**
closes #4245

### CODE REVIEW

File: packages/target-electron/build/afterPackHook.cjs [hunk 1]
```diff
@@ -102,8 +102,10 @@ module.exports = async context => {
 
   // copy map xdc
   // ---------------------------------------------------------------------------------
-  if (!env['NO_ASAR']) {
-    await copyMapXdcToUnpackedASAR(resources_dir, source_dir)
+  if (env['NO_ASAR']) {
+    await copyMapXdc(resources_dir, source_dir, false)
+  } else {
+    await copyMapXdc(resources_dir, source_dir, true)
   }
```
Comment (ralphtheninja) [inline packages/target-electron/build/afterPackHook.cjs:109]:
```suggestion
  const asar = env['NO_ASAR'] ? false : true
  await copyMapXdc(resources_dir, source_dir, asar)
```

Comment (ralphtheninja) [reply packages/target-electron/build/afterPackHook.cjs:109]: Mind adding a comment here describing why it looks like it does? What does `NO_ASAR` means? When should this be copied and when shouldn't it be copied?

Comment (Simon-Laux) [reply packages/target-electron/build/afterPackHook.cjs:109]: asar is some electron file archive format, no asar means not using it.

File: packages/target-electron/build/afterPackHook.cjs [hunk 2]
```diff
@@ -102,9 +102,8 @@ module.exports = async context => {
 
   // copy map xdc
   // ---------------------------------------------------------------------------------
-  if (!env['NO_ASAR']) {
-    await copyMapXdcToUnpackedASAR(resources_dir, source_dir)
-  }
+  const asar = env['NO_ASAR'] ? false : true
```
[the remark this answers is not in the document]
Comment (Simon-Laux) [reply packages/target-electron/build/afterPackHook.cjs:105]: @ralphtheninja like this?

**Review by nicodh — APPROVED** [review]
Didn't test. LGTM

File: packages/target-electron/build/afterPackHook.cjs (hunk 2 above)
[the remark this answers is not in the document]
Comment (ralphtheninja) [reply packages/target-electron/build/afterPackHook.cjs:106]: Yep. Perfect!

**Review by ralphtheninja — APPROVED** [review]
