### PR TITLE
fix: packaging: windows 64bit and 32bit releases now have different filenames

### LINKED ISSUE #3973: More recent versions than 1.44.1 package `app-32.7z` instead of `app-64.7z`
DeltaChat 1.44.1 still packaged `app-64.7z`, from 1.45.0 on it packages `app-32.7z`. Was that renamed on purpose?

- Operating System (Linux/Mac/Windows/iOS/Android): Windows 11
- Delta Chat Version: 1.44.1 - most recent
- Expected behavior: package `app-64.7z`
- Actual behavior: packages `app-32.7z`
- Steps to reproduce the problem: Download `DeltaChat.$version.exe` and unpack.
- Screenshots: 2024-06-24 11_40_39-0 INBOX
- Logs: None

### PR DESCRIPTION
**Pull request by Simon-Laux**
closes #3973

### CODE REVIEW

File: packages/target-electron/build/gen-electron-builder-config.js [hunk 1]
```diff
@@ -150,6 +150,7 @@ build['deb'] = {
 }
 
 build['win'] = {
+  artifactName: '${productName}-${version}.${arch}.${ext}',
```
Comment (r10s) [inline packages/target-electron/build/gen-electron-builder-config.js:153]: $arch is resoved to os/cpu then?

**Review by r10s — APPROVED** [review]
cannot say much to that, but lgtm so far :)

File: packages/target-electron/build/gen-electron-builder-config.js (hunk 1 above)
Comment (r10s) [reply packages/target-electron/build/gen-electron-builder-config.js:153]: answering myself: as it is only about windows here probably just "cpu"
