### PR TITLE
Copy files to tmpdir

### LINKED ISSUE #4352: Attachmentfiles on devices are rw - changes to attachements are not signaled to the user by DeltaChat
- Operating System (Linux/Mac/Windows/iOS/Android): Linux
- Delta Chat Version: 1.48

- Expected behavior:
If I click on an attachment (e.g. a LibreOffice document) sent to me via DeltaChat, DeltaChat either prompts me to save this to some folder on my device, or the attachment is opened directly in e.g. LibreOffice, but LibreOffice tells me, that the file is read-only and needs to be saved somewhere else before I can edit it.

- Actual behavior:
I click on an attachment in DeltaChat, attachment is opened directly in e.g. LibreOffice and I can edit & save directly to the attachment file in the DeltaChat storage location. Thus data between me and sender becomes inconsistent. DeltaChat does not inform me about the edited attachment.
Still worse is what happened to a friend of mine: He edited the document, saved it. The save was persistent, but only for a day or so. Then the changes in the document got reverted (by DeltaChat?) to the original version.

- Steps to reproduce the problem:
Open attachment in DeltaChat, edit, save (not "save as ..." but "save"). Then: reopen in DeltaChat. Edit is persistent, meaning attachment is not anymore in the state it was sent. DeltaChat does not inform user about this.
I was unable to reproduce the worse version on my machine. I believe what happened on my friends machine was due to him using a mail-server setup different from mine (him using the default DeltaChat-Server, me using my own mail provider).

- Screenshots: -
- Logs: -

- Comment: I know that one should save attachments to a different location before editing them, but there are many NOOBS out there and DeltaChats behaviour (see above) will get a lot of them in trouble. They should be able to use DeltaChat safely, I believe.

### LINKED ISSUE #4498: Adapt to file deduplication
We want to deduplicate blob files by always setting the file name to be the hash of the file content. Core issue: https://github.com/deltachat/deltachat-core-rust/issues/6265, core PR: https://github.com/deltachat/deltachat-core-rust/pull/6332

To be done:
- [x] When the user opens an attachment, copy it to a temp file with the correct name first https://github.com/deltachat/deltachat-desktop/issues/4352
- [ ] Make sure that the actual name of the file isn't shown to the user or used to determine the file type (via the extension), instead `dc_msg_get_filename()` (C-FFI) or `MessageObject.file_name` (JsonRPC) needs to be used, similar to the Android PR at https://github.com/deltachat/deltachat-android/pull/3521. 
  - Search for usages of `MessageObject.file`, check where it's passed, and make sure that all it's never used to check the file extension, to pass it to an external application, or to show it to the user.
  - Look at places in the code where a filename is user-visible, like when viewing it in the UI or passing it to an external application (especially when sharing or opening it). Check where the filename comes from, and make sure that it comes from `filename`, not from `file`.
  - Test that 
  1. sharing to and from DC
  2. opening
  3. saving ("Export attachment")
  4. drafting and re-entering the chat
  5. opening the drafted file once more
  6. sending
  
     still works for a) Images b) Videos c) vCards (attached contacts) d) attached files e) webxdc's. Also that editing and previewing drafted images works, and that previewing drafted videos works. (I hope I didn't forget to test any combination)

Then Desktop will be ready for using core with https://github.com/deltachat/deltachat-core-rust/pull/6332 merged. Received files will be deduplicated then, but outgoing files not yet.
 
For deduplicating outgoing files, I will need to add a new JsonRPC API or modify the existing one to use `set_file_and_deduplicate()` instead of `set_file()` (or alternatively, one of you could do that). I will need to ask one of you how you are using the API so that I can design it in a way that works well for you. And then of course, you will need to create a Desktop PR similar to https://github.com/deltachat/deltachat-android/pull/3513 that uses this new/changed API.
- A PR to modify the existing API: https://github.com/deltachat/deltachat-core-rust/pull/6470/

### PR DESCRIPTION
**Pull request by nicodh**
resolves #4498 
resolves #4352 

Files are copied to accounts/accountId/tmp/ before opening.

Files that have an ID from deduplication as name are copied to a folder with that name, to assure multiple files with same name do not conflict _tmp/fileId/originalFilename.ext_

On any start of the app all tmp dirs are deleted again

I didn't find any cases for second point in that issue "Make sure that the actual name of the file isn't shown to the user " - but that might also be checked in reviews

### CODE REVIEW

File: packages/frontend/src/components/message/messageFunctions.ts [hunk 1]
```diff
@@ -29,15 +29,17 @@ export function onDownload(msg: Type.Message) {
...
+  if (!msg.file || !msg.fileName) {
     log.error('message has no file to open:', msg)
     throw new Error('message has no file to open')
   }
-  if (!runtime.openPath(msg.file)) {
-    log.info(
-      "file couldn't be opened, try saving it in a different place and try to open it from there"
-    )
-  }
+  runtime.copyFileToInternalTmpDir(msg.fileName, msg.file).then(tmpFile => {
```
Comment (Simon-Laux) [inline packages/frontend/src/components/message/messageFunctions.ts:36]: nitpick: you can also make this function async as it does not return anything (to avoid additional nesting that comes from using then)

**Review by Simon-Laux — APPROVED** [review]

**Comment by nicodh** [comment]
> One possible concern is whether account deletion still works on windows if you currently have an attachment open in a different program?

The same for restarting the app with a file from tmp dir opened in some app
