### PR TITLE
fix: skip key arrow up if meta key is pressed

### LINKED ISSUE #5779: "Ctrl + Up to quote" shortcut doesn't work
- Operating System (Linux/Mac/Windows/iOS/Android): All
- Delta Chat Version: latest main

This has probably been introduced in https://github.com/deltachat/deltachat-desktop/pull/5713.

### PR DESCRIPTION
**Pull request by nicodh**
resolves #5779

### CODE REVIEW

File: packages/frontend/src/components/composer/ComposerMessageInput.tsx [hunk 1]
```diff
@@ -165,6 +165,8 @@ export default class ComposerMessageInput extends React.Component<
       e.stopPropagation()
     } else if (
       e.key === 'ArrowUp' &&
+      !e.ctrlKey &&
+      !e.metaKey &&
```
Comment (WofWca) [inline packages/frontend/src/components/composer/ComposerMessageInput.tsx:169]:
```suggestion
      !e.ctrlKey &&
      !e.metaKey &&
      !e.altKey &&
      !e.shiftKey &&
```

Otherwise the `Alt + ArrowUp` shortcut is also broken.
