### PR TITLE
Reset state when closing key transfer dialog

### LINKED ISSUE #636: Trying to send a autocrypt message a second time opens up old dialog
This isn't necessarily bad, but it's not possible to trigger a second sending of an autocrypt message.

How to reproduce: Send an autocrypt message, try to send a new one again :)

### PR DESCRIPTION
**Pull request by nicodh**
resolves #636

### CODE REVIEW

File: src/renderer/components/dialogs/KeyTransfer.js [hunk 1]
```diff
@@ -88,26 +89,32 @@ class KeyTransfer extends React.Component {
     ipcRenderer.removeListener('initiateKeyTransferResp', this.initiateKeyTransferResp)
   }
 
+  onClose () {
+    const { onClose } = this.props
+    this.setState({ key: null })
+    onClose()
```
Comment (ralphtheninja) [inline src/renderer/components/dialogs/KeyTransfer.js]: `this.props.onClose()`?
