### PR TITLE
fix: chat list switching between archive by itself

### LINKED ISSUE #6253: incoming messages alter selection in chatlist
since recently, incoming messages may alter the selection of the chatlist.

eg. 
- have a chat from the archive selected, eg. TESTCHAT
- navigate to another chat, by hitting the "back button" above the archive chats
- a new message arrives in TESTCHAT

-> chatlist changes back archive unexpectedly

this is unexpected.

the app should not play around with the selection the user did in the chatlist, esp. when it is only moments before. it can happen any time, however, happens more often when downloading messages.

iirc, there was some recent change in 2.48 or so, but i cannot find the exact chat

### PR DESCRIPTION
**Pull request by WofWca**
Closes https://github.com/deltachat/deltachat-desktop/issues/6253.

This bug has been introduced in
0bddb68a127f8626d81e8215c899a0c7bd94e8ce
(https://github.com/deltachat/deltachat-desktop/pull/5824).
The error is that `chatNoLinger` is `undefined` while
the chat is getting reloaded (`chatFetch.refresh`),
so `useHasChanged2()` returns `true` when the chat finishes refreshing,
whereas we only want to perform the "is archived?" check
on the initial load of the chat.

I have confirmed that this fixes the issue.

Edit: this could also be related to the archive switching bug that @ralphtheninja reported (see also https://github.com/deltachat/deltachat-desktop/issues/5993)

### CODE REVIEW

File: packages/frontend/src/contexts/ChatContext.tsx [hunk 1]
```diff
@@ -166,7 +166,17 @@ export const ChatProvider = ({
...
+  if (useHasChanged2(chatId) && chatId != undefined) {
+    // eslint-disable-next-line react-hooks/refs
+    isArchivedChecked.current = false
+  }
+  if (
+    // eslint-disable-next-line react-hooks/refs
+    !isArchivedChecked.current &&
+    chatNoLinger != undefined
+  ) {
+    isArchivedChecked.current = true
```
Comment (nicodh) [inline packages/frontend/src/contexts/ChatContext.tsx]: Why would something like this  not work? I tested and it fixed the issue


```suggestion
  const lastArchivedCheckChatId = useRef<number | undefined>(undefined)
  if (
    chatNoLinger != undefined &&
    // eslint-disable-next-line react-hooks/refs
    chatId !== lastArchivedCheckChatId.current
  ) {
    // eslint-disable-next-line react-hooks/refs
    lastArchivedCheckChatId.current = chatId
```

Comment (WofWca) [reply packages/frontend/src/contexts/ChatContext.tsx]: At a glance looks like it could work, but how is it better?

Comment (nicodh) [reply packages/frontend/src/contexts/ChatContext.tsx]: Simpler to read, no need for useHasChanged2

**Review by nicodh — CHANGES_REQUESTED** [review]
See inline comment

File: packages/frontend/src/contexts/ChatContext.tsx (hunk 1 above)
Comment (WofWca) [reply packages/frontend/src/contexts/ChatContext.tsx]: Hm, maybe maybe.

**Review by nicodh — APPROVED** [review]
