### PR TITLE
use `SOURCE_DATE_EPOCH` environment var for build timestamp instead of `Date.now()` if set.

### LINKED ISSUE #3944: Honor SOURCE_DATE_EPOCH for reproducibility
- Operating System (Linux/Mac/Windows/iOS/Android): Arch Linux
- Delta Chat Version: 1.46.0
- Expected behavior: Package is reproducible
- Actual behavior: Package is not reproducible
- Steps to reproduce the problem:
  - Build package for Arch Linux
  - Rebuild using [`repro`](https://github.com/archlinux/archlinux-repro)
- Code: The way `BUILD_TIMESTAMP` is set in https://github.com/deltachat/deltachat-desktop/blob/d16eb56771ee2d94c528d0ea4b0389a0d00c15b3/bin/build-shared-version-info.js#L54 is not reproducible, as it does not honor the [`SOURCE_DATE_EPOCH`](https://reproducible-builds.org/docs/source-date-epoch/) environment variable.
- Logs: The below logs are from [`diffoscope`](https://diffoscope.org/), comparing two built packages. We can observe, that differing `BUILD_TIMESTAMP` introduces a change, rendering the package not reproducible.

```
--- /tmp/rebuilderdqxdetU/inputs/deltachat-desktop-1.46.0-1-any.pkg.tar.zst
+++ /tmp/rebuilderdqxdetU/out/deltachat-desktop-1.46.0-1-any.pkg.tar.zst
├── deltachat-desktop-1.46.0-1-any.pkg.tar
│ ├── file list
│ │ @@ -1,9 +1,9 @@
│ │  -rw-r--r--   0 root         (0) root         (0)    11998 2024-06-11 10:01:13.000000 .BUILDINFO
│ │ --rw-r--r--   0 root         (0) root         (0)     1725 2024-06-11 10:01:13.000000 .MTREE
│ │ +-rw-r--r--   0 root         (0) root         (0)     1724 2024-06-11 10:01:13.000000 .MTREE
│ │  -rw-r--r--   0 root         (0) root         (0)      592 2024-06-11 10:01:13.000000 .PKGINFO
│ │  drwxr-xr-x   0 root         (0) root         (0)        0 2024-06-11 10:01:13.000000 usr/
│ │  drwxr-xr-x   0 root         (0) root         (0)        0 2024-06-11 10:01:13.000000 usr/bin/
│ │  -rwxr-xr-x   0 root         (0) root         (0)       86 2024-06-11 10:01:13.000000 usr/bin/deltachat-desktop
│ │  drwxr-xr-x   0 root         (0) root         (0)        0 2024-06-11 10:01:13.000000 usr/lib/
│ │  drwxr-xr-x   0 root         (0) root         (0)        0 2024-06-11 10:01:13.000000 usr/lib/deltachat-desktop/
│ │  -rw-r--r--   0 root         (0) root         (0)      105 2024-06-11 10:01:13.000000 usr/lib/deltachat-desktop/app-update.yml
│ ├── .MTREE
│ │ ├── .MTREE-content
│ │ │ @@ -6,15 +6,15 @@
│ │ │  ./usr time=1718100073.0 type=dir
│ │ │  ./usr/bin time=1718100073.0 type=dir
│ │ │  ./usr/bin/deltachat-desktop time=1718100073.0 size=86 sha256digest=d79c0245921ca8bf80f9f9d8e3ea1e2f20aa10144c0cbca68ef2e2717db41bf3
│ │ │  ./usr/lib time=1718100073.0 type=dir
│ │ │  /set mode=644
│ │ │  ./usr/lib/deltachat-desktop time=1718100073.0 mode=755 type=dir
│ │ │  ./usr/lib/deltachat-desktop/app-update.yml time=1718100073.0 size=105 sha256digest=d20a34d6fbeaa289c482ee035ddf9b0454657f48a2fe14803558f478f612f09c
│ │ │ -./usr/lib/deltachat-desktop/app.asar time=1718100073.0 size=67555533 sha256digest=26e2160428c2e3cf3f853336c272ca8feaf1f39709a8741e5431782f786dceab
│ │ │ +./usr/lib/deltachat-desktop/app.asar time=1718100073.0 size=67555533 sha256digest=b764c8147ab47e6b7a73cbe1c68ae7ec2b4b5133450e8c53738bf7345dc3c900
│ │ │  /set mode=755
│ │ │  ./usr/lib/deltachat-desktop/app.asar.unpacked time=1718100073.0 type=dir
│ │ │  ./usr/lib/deltachat-desktop/app.asar.unpacked/html-dist time=1718100073.0 type=dir
│ │ │  ./usr/lib/deltachat-desktop/app.asar.unpacked/html-dist/xdcs time=1718100073.0 type=dir
│ │ │  ./usr/lib/deltachat-desktop/app.asar.unpacked/html-dist/xdcs/maps.xdc time=1718100073.0 mode=644 size=52285 sha256digest=86566ab23340732e603ee30c89cf9edd10d94e7f34e15da380734470acc5017f
│ │ │  ./usr/lib/deltachat-desktop/app.asar.unpacked/node_modules time=1718100073.0 type=dir
│ │ │  ./usr/lib/deltachat-desktop/app.asar.unpacked/node_modules/@deltachat time=1718100073.0 type=dir
│ ├── usr/lib/deltachat-desktop/app.asar
│ │ @@ -248,25 +248,25 @@
│ │  00000f70: 7365 7422 3a22 3332 3338 3034 3333 227d  set":"32380433"}
│ │  00000f80: 2c22 7473 632d 6469 7374 223a 7b22 6669  ,"tsc-dist":{"fi
│ │  00000f90: 6c65 7322 3a7b 2273 6861 7265 6422 3a7b  les":{"shared":{
│ │  00000fa0: 2266 696c 6573 223a 7b22 6275 696c 642d  "files":{"build-
│ │  00000fb0: 696e 666f 2e6a 7322 3a7b 2273 697a 6522  info.js":{"size"
│ │  00000fc0: 3a31 3938 2c22 696e 7465 6772 6974 7922  :198,"integrity"
│ │  00000fd0: 3a7b 2261 6c67 6f72 6974 686d 223a 2253  :{"algorithm":"S
│ │ -00000fe0: 4841 3235 3622 2c22 6861 7368 223a 2239  HA256","hash":"9
│ │ -00000ff0: 3831 6134 6539 3963 3261 3635 6438 6365  81a4e99c2a65d8ce
│ │ -00001000: 6234 6363 3562 3437 6139 3635 3139 3032  b4cc5b47a9651902
│ │ -00001010: 3534 6439 6462 6239 3265 6231 6466 6366  54d9dbb92eb1dfcf
│ │ -00001020: 3866 6130 6437 3437 6261 3630 3232 3322  8fa0d747ba60223"
│ │ +00000fe0: 4841 3235 3622 2c22 6861 7368 223a 2235  HA256","hash":"5
│ │ +00000ff0: 6165 6166 3733 3462 3535 6136 3765 3837  aeaf734b55a67e87
│ │ +00001000: 3333 6636 3966 6331 3661 6536 3132 6637  33f69fc16ae612f7
│ │ +00001010: 6234 3465 3366 3537 3335 6334 3637 3832  b44e3f5735c46782
│ │ +00001020: 3062 3635 3336 3032 6233 6633 3336 6522  0b653602b3f336e"
│ │  00001030: 2c22 626c 6f63 6b53 697a 6522 3a34 3139  ,"blockSize":419
│ │  00001040: 3433 3034 2c22 626c 6f63 6b73 223a 5b22  4304,"blocks":["
│ │ -00001050: 3938 3161 3465 3939 6332 6136 3564 3863  981a4e99c2a65d8c
│ │ -00001060: 6562 3463 6335 6234 3761 3936 3531 3930  eb4cc5b47a965190
│ │ -00001070: 3235 3464 3964 6262 3932 6562 3164 6663  254d9dbb92eb1dfc
│ │ -00001080: 6638 6661 3064 3734 3762 6136 3032 3233  f8fa0d747ba60223
│ │ +00001050: 3561 6561 6637 3334 6235 3561 3637 6538  5aeaf734b55a67e8
│ │ +00001060: 3733 3366 3639 6663 3136 6165 3631 3266  733f69fc16ae612f
│ │ +00001070: 3762 3434 6533 6635 3733 3563 3436 3738  7b44e3f5735c4678
│ │ +00001080: 3230 6236 3533 3630 3262 3366 3333 3665  20b653602b3f336e
│ │  00001090: 225d 7d2c 226f 6666 7365 7422 3a22 3332  "]},"offset":"32
│ │  000010a0: 3338 3034 3933 227d 2c22 6275 696c 642d  380493"},"build-
│ │  000010b0: 696e 666f 2e6a 732e 6d61 7022 3a7b 2273  info.js.map":{"s
│ │  000010c0: 697a 6522 3a32 3536 2c22 696e 7465 6772  ize":256,"integr
│ │  000010d0: 6974 7922 3a7b 2261 6c67 6f72 6974 686d  ity":{"algorithm
│ │  000010e0: 223a 2253 4841 3235 3622 2c22 6861 7368  ":"SHA256","hash
│ │  000010f0: 223a 2236 6664 3137 6133 6262 3765 6636  ":"6fd17a3bb7ef6
│ │ @@ -3579,29 +3579,29 @@
│ │  0000dfa0: 3461 6462 3337 6631 3239 3761 6236 3262  4adb37f1297ab62b
│ │  0000dfb0: 6631 6136 6465 6636 225d 7d2c 226f 6666  f1a6def6"]},"off
│ │  0000dfc0: 7365 7422 3a22 3338 3132 3936 3931 227d  set":"38129691"}
│ │  0000dfd0: 2c22 6275 6e64 6c65 2e6a 732e 6d61 7022  ,"bundle.js.map"
│ │  0000dfe0: 3a7b 2273 697a 6522 3a36 3637 3238 3731  :{"size":6672871
│ │  0000dff0: 2c22 696e 7465 6772 6974 7922 3a7b 2261  ,"integrity":{"a
│ │  0000e000: 6c67 6f72 6974 686d 223a 2253 4841 3235  lgorithm":"SHA25
│ │ -0000e010: 3622 2c22 6861 7368 223a 2236 6661 3265  6","hash":"6fa2e
│ │ -0000e020: 6532 3333 6663 3737 3232 6631 6262 3036  e233fc7722f1bb06
│ │ -0000e030: 3831 3865 3233 6565 6661 6430 3935 3436  818e23eefad09546
│ │ -0000e040: 6335 6361 3134 6266 6235 6138 3363 6338  c5ca14bfb5a83cc8
│ │ -0000e050: 3439 3664 3136 6330 6331 3822 2c22 626c  496d16c0c18","bl
│ │ +0000e010: 3622 2c22 6861 7368 223a 2232 3162 6163  6","hash":"21bac
│ │ +0000e020: 3735 3930 6333 6339 6435 3237 3130 3433  7590c3c9d5271043
│ │ +0000e030: 3236 3464 6233 6439 3335 3064 3838 6535  264db3d9350d88e5
│ │ +0000e040: 3163 6331 3263 3537 6162 3436 3034 3164  1cc12c57ab46041d
│ │ +0000e050: 3131 3362 3930 3637 3462 3622 2c22 626c  113b90674b6","bl
│ │  0000e060: 6f63 6b53 697a 6522 3a34 3139 3433 3034  ockSize":4194304
│ │  0000e070: 2c22 626c 6f63 6b73 223a 5b22 6266 6432  ,"blocks":["bfd2
│ │  0000e080: 3063 3532 3339 3737 3663 6638 6433 3332  0c5239776cf8d332
│ │  0000e090: 3036 3965 6331 3362 3339 3365 3438 6230  069ec13b393e48b0
│ │  0000e0a0: 6466 3733 6366 3337 3937 3131 3163 6165  df73cf3797111cae
│ │ -0000e0b0: 6538 3430 6537 3037 6264 3732 222c 2234  e840e707bd72","4
│ │ -0000e0c0: 6365 3730 3431 6163 3762 3430 6562 3664  ce7041ac7b40eb6d
│ │ -0000e0d0: 3761 3833 3565 6337 3631 6439 3762 3838  7a835ec761d97b88
│ │ -0000e0e0: 3461 3366 3066 3964 3236 3864 3034 6238  4a3f0f9d268d04b8
│ │ -0000e0f0: 3735 3534 6237 3233 3164 3461 6134 6222  7554b7231d4aa4b"
│ │ +0000e0b0: 6538 3430 6537 3037 6264 3732 222c 2232  e840e707bd72","2
│ │ +0000e0c0: 6435 3431 6334 3435 3762 6165 3264 3734  d541c4457bae2d74
│ │ +0000e0d0: 3332 6637 3332 6562 6331 3837 3837 3366  32f732ebc187873f
│ │ +0000e0e0: 6464 6637 6337 3335 6266 3762 6333 3333  ddf7c735bf7bc333
│ │ +0000e0f0: 6539 3363 3831 6537 6439 3032 6339 3022  e93c81e7d902c90"
│ │  0000e100: 5d7d 2c22 6f66 6673 6574 223a 2234 3037  ]},"offset":"407
│ │  0000e110: 3335 3330 3122 7d2c 2266 616c 6c62 6163  35301"},"fallbac
│ │  0000e120: 6b2d 7468 656d 652e 6373 7322 3a7b 2273  k-theme.css":{"s
│ │  0000e130: 697a 6522 3a37 3230 352c 2269 6e74 6567  ize":7205,"integ
│ │  0000e140: 7269 7479 223a 7b22 616c 676f 7269 7468  rity":{"algorith
│ │  0000e150: 6d22 3a22 5348 4132 3536 222c 2268 6173  m":"SHA256","has
│ │  0000e160: 6822 3a22 3534 3839 3931 3964 6666 3933  h":"5489919dff93
│ │ @@ -30637,16 +30637,16 @@
│ │  00077ac0: 6c69 6e65 0a2f 2f2f 2047 454e 4552 4154  line./// GENERAT
│ │  00077ad0: 4544 2046 494c 4520 7275 6e20 606e 706d  ED FILE run `npm
│ │  00077ae0: 2072 756e 2062 7569 6c64 6020 746f 2072   run build` to r
│ │  00077af0: 6566 7265 7368 0a65 7870 6f72 7420 636f  efresh.export co
│ │  00077b00: 6e73 7420 5645 5253 494f 4e20 3d20 2731  nst VERSION = '1
│ │  00077b10: 2e34 362e 3027 3b0a 6578 706f 7274 2063  .46.0';.export c
│ │  00077b20: 6f6e 7374 2042 5549 4c44 5f54 494d 4553  onst BUILD_TIMES
│ │ -00077b30: 5441 4d50 203d 2031 3731 3831 3030 3130  TAMP = 171810010
│ │ -00077b40: 3839 3932 3b0a 6578 706f 7274 2063 6f6e  8992;.export con
│ │ +00077b30: 5441 4d50 203d 2031 3731 3831 3030 3632  TAMP = 171810062
│ │ +00077b40: 3936 3330 3b0a 6578 706f 7274 2063 6f6e  9630;.export con
│ │  00077b50: 7374 2047 4954 5f52 4546 203d 2027 6e6f  st GIT_REF = 'no
│ │  00077b60: 6e65 273b 0a2f 2f23 2073 6f75 7263 654d  ne';.//# sourceM
│ │  00077b70: 6170 7069 6e67 5552 4c3d 6275 696c 642d  appingURL=build-
│ │  00077b80: 696e 666f 2e6a 732e 6d61 707b 2276 6572  info.js.map{"ver
│ │  00077b90: 7369 6f6e 223a 332c 2266 696c 6522 3a22  sion":3,"file":"
│ │  00077ba0: 6275 696c 642d 696e 666f 2e6a 7322 2c22  build-info.js","
│ │  00077bb0: 736f 7572 6365 526f 6f74 223a 2222 2c22  sourceRoot":"","
│ │ @@ -831271,15 +831271,15 @@
│ │  00caf260: 4745 4e45 5241 5445 4420 4649 4c45 2072  GENERATED FILE r
│ │  00caf270: 756e 2060 6e70 6d20 7275 6e20 6275 696c  un `npm run buil
│ │  00caf280: 6460 2074 6f20 7265 6672 6573 685c 6e65  d` to refresh\ne
│ │  00caf290: 7870 6f72 7420 636f 6e73 7420 5645 5253  xport const VERS
│ │  00caf2a0: 494f 4e20 3d20 2731 2e34 362e 3027 5c6e  ION = '1.46.0'\n
│ │  00caf2b0: 6578 706f 7274 2063 6f6e 7374 2042 5549  export const BUI
│ │  00caf2c0: 4c44 5f54 494d 4553 5441 4d50 203d 2031  LD_TIMESTAMP = 1
│ │ -00caf2d0: 3731 3831 3030 3130 3839 3932 5c6e 6578  718100108992\nex
│ │ +00caf2d0: 3731 3831 3030 3632 3936 3330 5c6e 6578  718100629630\nex
│ │  00caf2e0: 706f 7274 2063 6f6e 7374 2047 4954 5f52  port const GIT_R
│ │  00caf2f0: 4546 203d 2027 6e6f 6e65 275c 6e22 2c20  EF = 'none'\n", 
│ │  00caf300: 2269 6d70 6f72 7420 5265 6163 7420 6672  "import React fr
│ │  00caf310: 6f6d 2027 7265 6163 7427 5c6e 5c6e 696d  om 'react'\n\nim
│ │  00caf320: 706f 7274 2075 7365 5472 616e 736c 6174  port useTranslat
│ │  00caf330: 696f 6e46 756e 6374 696f 6e20 6672 6f6d  ionFunction from
│ │  00caf340: 2027 2e2e 2f2e 2e2f 686f 6f6b 732f 7573   '../../hooks/us
│ │ @@ -2035155,15 +2035155,15 @@
│ │  01f0dd20: 4552 4154 4544 2046 494c 4520 7275 6e20  ERATED FILE run 
│ │  01f0dd30: 606e 706d 2072 756e 2062 7569 6c64 6020  `npm run build` 
│ │  01f0dd40: 746f 2072 6566 7265 7368 0a65 7870 6f72  to refresh.expor
│ │  01f0dd50: 7420 636f 6e73 7420 5645 5253 494f 4e20  t const VERSION 
│ │  01f0dd60: 3d20 2731 2e34 362e 3027 3b0a 6578 706f  = '1.46.0';.expo
│ │  01f0dd70: 7274 2063 6f6e 7374 2042 5549 4c44 5f54  rt const BUILD_T
│ │  01f0dd80: 494d 4553 5441 4d50 203d 2031 3731 3831  IMESTAMP = 17181
│ │ -01f0dd90: 3030 3130 3839 3932 3b0a 6578 706f 7274  00108992;.export
│ │ +01f0dd90: 3030 3632 3936 3330 3b0a 6578 706f 7274  00629630;.export
│ │  01f0dda0: 2063 6f6e 7374 2047 4954 5f52 4546 203d   const GIT_REF =
│ │  01f0ddb0: 2027 6e6f 6e65 273b 0a2f 2f23 2073 6f75   'none';.//# sou
│ │  01f0ddc0: 7263 654d 6170 7069 6e67 5552 4c3d 6275  rceMappingURL=bu
│ │  01f0ddd0: 696c 642d 696e 666f 2e6a 732e 6d61 707b  ild-info.js.map{
│ │  01f0dde0: 2276 6572 7369 6f6e 223a 332c 2266 696c  "version":3,"fil
│ │  01f0ddf0: 6522 3a22 6275 696c 642d 696e 666f 2e6a  e":"build-info.j
│ │  01f0de00: 7322 2c22 736f 7572 6365 526f 6f74 223a  s","sourceRoot":
│ │ @@ -2835788,15 +2835788,15 @@
│ │  02b454b0: 2f2f 2f20 4745 4e45 5241 5445 4420 4649  /// GENERATED FI
│ │  02b454c0: 4c45 2072 756e 2060 6e70 6d20 7275 6e20  LE run `npm run 
│ │  02b454d0: 6275 696c 6460 2074 6f20 7265 6672 6573  build` to refres
│ │  02b454e0: 685c 6e65 7870 6f72 7420 636f 6e73 7420  h\nexport const 
│ │  02b454f0: 5645 5253 494f 4e20 3d20 2731 2e34 362e  VERSION = '1.46.
│ │  02b45500: 3027 5c6e 6578 706f 7274 2063 6f6e 7374  0'\nexport const
│ │  02b45510: 2042 5549 4c44 5f54 494d 4553 5441 4d50   BUILD_TIMESTAMP
│ │ -02b45520: 203d 2031 3731 3831 3030 3130 3839 3932   = 1718100108992
│ │ +02b45520: 203d 2031 3731 3831 3030 3632 3936 3330   = 1718100629630
│ │  02b45530: 5c6e 6578 706f 7274 2063 6f6e 7374 2047  \nexport const G
│ │  02b45540: 4954 5f52 4546 203d 2027 6e6f 6e65 275c  IT_REF = 'none'\
│ │  02b45550: 6e22 2c20 2269 6d70 6f72 7420 5265 6163  n", "import Reac
│ │  02b45560: 7420 6672 6f6d 2027 7265 6163 7427 5c6e  t from 'react'\n
│ │  02b45570: 5c6e 696d 706f 7274 2075 7365 5472 616e  \nimport useTran
│ │  02b45580: 736c 6174 696f 6e46 756e 6374 696f 6e20  slationFunction 
│ │  02b45590: 6672 6f6d 2027 2e2e 2f2e 2e2f 686f 6f6b  from '../../hook
│ │ @@ -4194297,8 +4194297,8 @@
│ │  03ffff80: 6e64 6578 5d3b 0a09 2020 2020 7d0a 0a09  ndex];..    }...
│ │  03ffff90: 2020 2020 7661 7220 7265 6c61 7469 7665      var relative
│ │  03ffffa0: 536f 7572 6365 203d 2061 536f 7572 6365  Source = aSource
│ │  03ffffb0: 3b0a 0920 2020 2069 6620 2874 6869 732e  ;..    if (this.
│ │  03ffffc0: 736f 7572 6365 526f 6f74 2021 3d20 6e75  sourceRoot != nu
│ │  03ffffd0: 6c6c 2920 7b0a 0920 2020 2020 2072 656c  ll) {..      rel
│ │  03ffffe0: 6174 6976 6553 6f75 7263 6520 3d20 7574  ativeSource = ut
│ │ -[ Too much input for diff (SHA256: 8798d6c7835b97b2514f1f0bc92c9611881eb78f536861d36ce6d57b8d3e73ea) ]
│ │ +[ Too much input for diff (SHA256: 3dc191eed9db49f2e3f179957f9b3d8beb6142ff9175b3be9438bf2134d3a503) ]

```

### PR DESCRIPTION
**Pull request by Simon-Laux**
This should help in making builds reproducible.

closes #3944

### CODE REVIEW

File: bin/build-shared-version-info.js [hunk 1]
```diff
@@ -51,7 +51,7 @@ async function gatherBuildInfo() {
   const packageObject = JSON.parse(await readFile(packageJSON, 'utf8'))
   return {
     VERSION: packageObject.version,
-    BUILD_TIMESTAMP: Date.now(),
+    BUILD_TIMESTAMP: process.env.SOURCE_DATE_EPOCH || Date.now(),
```
Comment (dvzrv) [inline bin/build-shared-version-info.js:54]: I think this should work (I can test locally in a bit).
In https://reproducible-builds.org/docs/source-date-epoch/ they suggest the below (and I don't know the difference between `Date.now()` and `new Date().getTime()`, but from looking at your change though I am assuming that currently it would be  `String` when using the environment variable and an `Integer` when using the function call - is that intentional?).

```javascript
var timestamp = new Date(process.env.SOURCE_DATE_EPOCH ? (process.env.SOURCE_DATE_EPOCH * 1000) : new Date().getTime());

// Alternatively, to ensure a fixed timezone:

var now = new Date();
if (process.env.SOURCE_DATE_EPOCH) {
  now = new Date((process.env.SOURCE_DATE_EPOCH * 1000) + (now.getTimezoneOffset() * 60000));
}
```

**Comment by dvzrv** [comment]
Apart from my comment about the data type etc. I can confirm, that this change makes the build reproducible! :tada:

File: bin/build-shared-version-info.js (hunk 1 above)
Comment (Simon-Laux) [reply bin/build-shared-version-info.js:54]: interesting to know that timestamp is in seconds instead of milliseconds. anyways does not matter much, because currently this is just used for logging it at app startup
