### PR TITLE
Fetch webxdc info seperately with `rpc.getWebxdcInfo`, because new core will no longer provide it in the MessageObject

### LINKED ISSUE #5218: Call get_webxdc_info() to get webxdc info
Since core 1.160.0 Message.webxdc_info is removed as loading it may fail loading the whole message: https://github.com/chatmail/core/pull/6920

Now desktop needs to call `get_webxdc_info` as a separate call and process errors, e.g. show the Webxdc message as a file or something like this if .xdc file turns out not to be a proper Webxdc file or if there is a temporary error.

### PR DESCRIPTION
**Pull request by nicodh**
Resolves #5218 

I already tested various stuff, only thing I'm not really sure about is if broken media handling in Gallery is still the same as before, as I didn't had the various use cases

### CODE REVIEW

**Comment by WofWca** [comment]
https://github.com/deltachat/deltachat-desktop/pull/5222 would be great and cutting down the amount of lines here.

**Comment by WofWca** [comment]
@nicodh do you want to rewrite this with the new `useRpcFetch` or shall I review as is?

**Comment by Simon-Laux** [comment]
Does this really require a new core? from what I can tell the direct api is already available in the core we use.
(it just removes the (premature) performance optimisation of directly returning the webxdc info with the message object, that caused some issues somewhere)
So I think we can already merge this?

**Comment by nicodh** [comment]
Ok, just checked it: it's the other way round: 1.160.0 core will not run without this changes. So I think it makes sense to merge this first and then do the upgrade to core 1.160.

**Comment by nicodh** [comment]
> @nicodh do you want to rewrite this with the new `useRpcFetch` or shall I review as is?

Please review as it is. I will adapt in a separate PR to new useRpcFetch.

File: packages/frontend/src/components/attachment/messageAttachment.tsx [hunk 1]
```diff
@@ -234,6 +235,32 @@ export function DraftAttachment({
...
+            attachment.id,
+            error
+          )
+          setWebxdcInfo(null)
+        })
+        .finally(() => {
+          setIsLoadingWebxdcInfo(false)
+        })
+    }
+  }, [accountId, attachment, attachment.id, attachment.viewType])
```
Comment (WofWca) [inline packages/frontend/src/components/attachment/messageAttachment.tsx]: Having `attachment` (draft message) as dependency makes it re-run the effect every time the draft changes, leading to jumpiness

File: packages/frontend/src/system-integration/webxdc.ts [hunk 2]
```diff
@@ -37,7 +37,8 @@ export async function internalOpenWebxdc(
     messageId = message.parentId
     message = await BackendRemote.rpc.getMessage(accountId, messageId)
   }
-  if (!message.webxdcInfo) {
+  const webxdcInfo = await BackendRemote.rpc.getWebxdcInfo(accountId, messageId)
```
Comment (WofWca) [inline packages/frontend/src/system-integration/webxdc.ts]: For better performance, `internalOpenWebxdc` should accept `webxdcInfo`, at least optionally, because it's already available most (if not all) of the time.

File: packages/frontend/src/components/message/Message.tsx [hunk 3]
```diff
@@ -1114,13 +1114,40 @@ function WebxdcMessageContent({
   tabindexForInteractiveContents: -1 | 0
 }) {
   const tx = useTranslationFunction()
+  const [webxdcInfo, setWebxdcInfo] = useState<T.WebxdcMessageInfo | null>(null)
+  const [isLoadingWebxdcInfo, setIsLoadingWebxdcInfo] = useState(false)
+  const accountId = selectedAccountId()
+
+  useEffect(() => {
```
Comment (WofWca) [inline packages/frontend/src/components/message/Message.tsx]: Looks like we need to listen on `MsgsChanged` around here, because otherwise the message info doesn't update live, e.g. with the Editor app. Try sending one, and then typing something. After that, the updates will only appear when you switch the chat.

And maybe the same goes for all other places where apps are displayed, e.g. gallery?

image

File: packages/frontend/src/components/message/Message.tsx [hunk 4]
```diff
@@ -1114,13 +1114,40 @@ function WebxdcMessageContent({
...
+  }, [accountId, message.id, message.viewType])
+
   if (message.viewType !== 'Webxdc') {
     return null
   }
-  const info = message.webxdcInfo || {
-    name: 'INFO MISSING!',
+
+  const info = webxdcInfo || {
+    name: isLoadingWebxdcInfo ? 'Loading...' : 'INFO MISSING!',
```
Comment (WofWca) [inline packages/frontend/src/components/message/Message.tsx:1176]: At certain screen widths, the "loading..." text is shorter (height-wise) than the text after the eventual load of the app, which results in the infamous "chat is not scrolled all the way to the bottom when you open it" bug. See
- https://github.com/deltachat/deltachat-desktop/issues/4404
- https://github.com/deltachat/deltachat-desktop/issues/3763
- https://github.com/deltachat/deltachat-desktop/issues/3753
- https://github.com/deltachat/deltachat-desktop/issues/4698

image

I think we either have to wait for message info to load in `messagelist.ts`, basically reverting the core change that caused this MR, or ensure that the webxdc message never gets taller when `webxdcInfo` eventually loads. This could be achieved by either hard-coding the message height for the top portion of a webxdc message (i.e. everything besides the message text), as we did for images not so long ago, or by making the app title and the "summary" never wrap. But keep in mind that the summary could be missing (and it is missing by default for a freshly sent app).
This will also solve the problem with height changes that occur later on, after the message list has been fully loaded, upon `webxdc.sendUpdate({ document, summary})` calls.

File: packages/frontend/src/components/attachment/mediaAttachment.tsx [hunk 5]
```diff
@@ -609,44 +610,97 @@ export function WebxdcAttachment({
...
     const onContextMenu = getBrokenMediaContextMenu(
       contextMenu.openContextMenu,
       openDialog,
       deleteMessage,
       messageId,
       accountId
     )
-    // webxdc info is not set, show different error
-    log.error('message.webxdcInfo is undefined, msgid:', messageId)
+    log.error('webxdcInfo is not available, msgid:', messageId)
```
Comment (WofWca) [inline packages/frontend/src/components/attachment/mediaAttachment.tsx:661]: Hm actually I forgot to check out this file.

This error gets printed for each message upon the initial render. Looks like `isLoadingWebxdcInfo` should be `true` initially, and the same goes for all other places I think.

File: packages/frontend/src/components/attachment/mediaAttachment.tsx [hunk 6]
```diff
@@ -609,44 +610,97 @@ export function WebxdcAttachment({
...
+      >
+        <img
+          className='icon'
+          src={runtime.getWebxdcIconURL(selectedAccountId(), messageId)}
+        />
+        <div className='text-part'>
+          <div className='name'>Loading...</div>
+          <div className='summary'></div>
+        </div>
+      </div>
```
Comment (WofWca) [inline packages/frontend/src/components/attachment/mediaAttachment.tsx]: It would be nice not to copy-paste this.

**Comment by Simon-Laux** [comment]
I changed pr title because it was confusing me again - the `rpc.getWebxdcInfo` api is not new.

File: packages/frontend/src/components/attachment/messageAttachment.tsx (hunk 1 above)
Comment (nicodh) [reply packages/frontend/src/components/attachment/messageAttachment.tsx]: Addressed in 0fbe7dc09745a33a08d45f306b42a3c7b27bf829

File: packages/frontend/src/system-integration/webxdc.ts (hunk 2 above)
Comment (nicodh) [reply packages/frontend/src/system-integration/webxdc.ts]: Adressed in 6e441010042ecf17343c43fa008f2bdc97be8b18

File: packages/frontend/src/components/message/Message.tsx (hunk 3 above)
Comment (nicodh) [reply packages/frontend/src/components/message/Message.tsx]: I added a listener for event WebxdcStatusUpdate 554c6bea556830990a3e23e12f6a244af312d562

File: packages/frontend/src/components/attachment/mediaAttachment.tsx (hunk 5 above)
Comment (nicodh) [reply packages/frontend/src/components/attachment/mediaAttachment.tsx:661]: mediaAttachment was refactored to use the new rpcFetch...
Other use cases are  in DraftAttachment and WebxdcMessageContent where isLoadingWebxdcInfo is set anyway

File: packages/frontend/src/components/attachment/mediaAttachment.tsx (hunk 6 above)
Comment (nicodh) [reply packages/frontend/src/components/attachment/mediaAttachment.tsx]: I agree but that should go into another PR - this PR is already pretty overloaded anyway

File: packages/frontend/src/components/attachment/messageAttachment.tsx (hunk 1 above)
Comment (WofWca) [reply packages/frontend/src/components/attachment/messageAttachment.tsx]: Oh, right. We're making a new message on almost every key stroke...

In that case I guess not showing "Loading..." would solve the jumpiness problem, until we get around to implementing proper draft saving.

> Addressed in https://github.com/deltachat/deltachat-desktop/commit/0fbe7dc09745a33a08d45f306b42a3c7b27bf829

Relying on filename now seems wrong, but I guess it's not that big of a potential bug.

File: packages/frontend/src/components/message/Message.tsx (hunk 4 above)
Comment (nicodh) [reply packages/frontend/src/components/message/Message.tsx:1176]: I think this shopuld be solved by applying the right media query breakpoints.
Like with images it seems there are some rules applied earlier than others where both should use the same breakpoint.
I will have a look but that could also go into a separate PR imho

File: packages/frontend/src/components/message/Message.tsx (hunk 3 above)
Comment (nicodh) [reply packages/frontend/src/components/message/Message.tsx]: The same applies to mediaAttachement in Gallery where the content is also not updated when WebxdcStatusUpdate events happen, but that could maybe adresses in a followup since the use case to have the app and gallery open at the same time is probably more rare

File: packages/frontend/src/components/attachment/mediaAttachment.tsx (hunk 5 above)
Comment (WofWca) [reply packages/frontend/src/components/attachment/mediaAttachment.tsx:661]: > where isLoadingWebxdcInfo is set anyway

Is it? It's initialized to `false` in those places, only until the `useEffect` runs. But fine I guess.

File: packages/frontend/src/components/attachment/mediaAttachment.tsx [hunk 7]
```diff
@@ -609,44 +609,84 @@ export function WebxdcAttachment({
...
+        ref={interactiveElRef}
+        className={'media-attachment-webxdc ' + rovingTabindex.className}
+        {...rovingTabindexProps}
+      >
+        <img
+          className='icon'
+          src={runtime.getWebxdcIconURL(selectedAccountId(), messageId)}
+        />
+        <div className='text-part'>
+          <div className='name'>Loading...</div>
```
Comment (WofWca) [inline packages/frontend/src/components/attachment/mediaAttachment.tsx]: This is wrong. `loadResult` is never falsy, and `loadResult.kind !== 'message'` only leaves `kind === "loadingError"`. So it's not a "loading" state.

Comment (nicodh) [reply packages/frontend/src/components/attachment/mediaAttachment.tsx]: You are right! I removed it in 7b44c5aca56f068db15a15f67059b9d87465ed85

File: packages/frontend/src/components/message/Message.tsx (hunk 3 above)
Comment (WofWca) [reply packages/frontend/src/components/message/Message.tsx]: Do you think `WebxdcStatusUpdate` is better than `MsgsChanged` for this?

File: packages/frontend/src/components/attachment/mediaAttachment.tsx [hunk 8]
```diff
@@ -609,44 +609,61 @@ export function WebxdcAttachment({
...
       messageId,
       accountId
     )
-
     return (
       <div
         ref={interactiveElRef}
-        className={'media-attachment-webxdc broken ' + rovingTabindex.className}
-        title={loadResult.error}
+        className={'media-attachment-webxdc ' + rovingTabindex.className}
```
Comment (WofWca) [inline packages/frontend/src/components/attachment/mediaAttachment.tsx:639]: > only thing I'm not really sure about is if broken media handling in Gallery is still the same as before, as I didn't had the various use cases

Indeed it's not the same.

- `getBrokenMediaContextMenu` is used for the "loading" state.
- `loadResult.error` is not used anymore.
- `tx('attachment_failed_to_load')` is not used, intead 'webxdcInfo is not available' is shown in both cases.

But it's not super important I guess.
