### PR TITLE
fix: blur buttons in dialogs

### LINKED ISSUE #5696: "enter" acts as "escape" in some dialogs; this seems unexpected
- right tap a chat
- select "delete" from the context menu
- hit "enter" key

-> as the dialog disappears one would expect that the "delete" action, as being rightmost and outstanding button was confirmed.

but actually nothing has happened - which may lead to the situation that the user believes they deleted smth but actually did not.

i see the point that an accidental hitting of enter may be worse as well, and also the outstanding button is great, and no-focus-by-default is fine as well, all that should not change.

to fix the issue, i would just do nothing if "Enter" is hit and no button is focused.

that would make it clear to the user that no action was taken place - if they want to do nothing, they should hit "Escape" - and if they actually want to delete, hit "tab -> enter" or click the button

### PR DESCRIPTION
**Pull request by nicodh**
resolves #5696

After some discussions: with this PR we just avoid to have a default focus in dialogs except where it is wanted (for example in Instinct Onboarding where we want to focus the "Create Profile" button and the name input field).

Now enter does not trigger the first focusable element in dialogs so it has no effect at all, except when the user tabs the focus to an element.

### CODE REVIEW

**Comment by nicodh** [comment]
tbd: we could also skip the blur for alert dialogs so that enter/space would close them

File: packages/frontend/src/components/Dialog/Dialog.tsx [hunk 1]
```diff
@@ -20,6 +20,7 @@ type Props = React.PropsWithChildren<{
   // takes full screen and is transparent
   unstyled?: boolean
   dataTestid?: string
+  skipAutoBlur?: boolean
```
Comment (WofWca) [inline packages/frontend/src/components/Dialog/Dialog.tsx]: I'd add a comment about why we do it.

File: packages/frontend/src/components/Dialog/Dialog.tsx [hunk 2]
```diff
@@ -83,6 +85,10 @@ const Dialog = React.memo<Props>(
       // calling showModal is "only" the way to have ::backdrop
       dialog.current?.showModal()
       dialog.current!.style.display = 'flex'
+      // Remove focus from any auto-focused element
+      if (!skipAutoBlur && document.activeElement instanceof HTMLElement) {
+        document.activeElement.blur()
+      }
```
Comment (WofWca) [inline packages/frontend/src/components/Dialog/Dialog.tsx]: This breaks things. It's executed every time a dialog is re-rendered, so e.g. if a dialog contains an input, it gets blurred on every key press. For example, see the "add members" dialog.

Perhaps moving this inside of a separate `useEffect` with empty dependencies (or just `skipAutoBlur`) should work.

Comment (nicodh) [reply packages/frontend/src/components/Dialog/Dialog.tsx]: Well it is already in a useEffect but I didn't see that the dependency was missing in the existing code which is a bit strange.

I will add it and add some conditions for the element type

File: packages/frontend/src/components/screens/WelcomeScreen/index.tsx [hunk 3]
```diff
@@ -73,6 +73,7 @@ export default function WelcomeScreen({ selectedAccountId, ...props }: Props) {
         canOutsideClickClose={false}
         onClose={onClose}
         dataTestid='onboarding-dialog'
+        allowDefaultFocus={true}
```
Comment (nicodh) [inline packages/frontend/src/components/screens/WelcomeScreen/index.tsx:76]: So far this is the only place where this prop makes sense: it will focus the "Create Account" button which is the primary action for the InstantOnboarding Screen

File: packages/frontend/src/components/Dialog/Dialog.tsx [hunk 4]
```diff
@@ -93,7 +88,23 @@ const Dialog = React.memo<Props>(
...
+          )
+
+        if (
+          (tagName === 'button' || isButtonLikeInput) &&
+          !document.activeElement.hasAttribute('autofocus')
+        ) {
+          // Remove focus from auto-focused buttons or button like elements
+          document.activeElement.blur()
+        }
+      }
```
Comment (WofWca) [inline packages/frontend/src/components/Dialog/Dialog.tsx:109]: This should be inside a separate `useEffect` because otherwise `showModal()` depends on `allowDefautFocus` for no apparent reason.

File: packages/frontend/src/components/Dialog/Dialog.tsx [hunk 5]
```diff
@@ -30,6 +20,10 @@ type Props = React.PropsWithChildren<{
   // takes full screen and is transparent
   unstyled?: boolean
   dataTestid?: string
+  /** per default the first element in a modal dialog is focused
+   * but we remove that focus to avoid unexpected behaviours
+   * set this to true to keep the default focus behavior */
```
Comment (WofWca) [inline packages/frontend/src/components/Dialog/Dialog.tsx]:
```suggestion
   * but we remove that focus so that e.g. the user doesn't press a button
   * (with Space or Enter) which they have not explicitly focused,
   * for example the "cancel" button in the "Delete Chat?" dialog.
   * set this to true to keep the default focus behavior.
   *
   * We only prevent focus on button elements,
   * so if the first element in the dialog is e.g. a text input,
   * this prop has no effect */
```

**Review by WofWca — APPROVED** [review]
Alright, the bug seems to have been fixed (although I didn't re-test), and the behavior is more conservative than on my last review.

File: packages/frontend/src/components/Dialog/Dialog.tsx (hunk 4 above)
Comment (nicodh) [reply packages/frontend/src/components/Dialog/Dialog.tsx:109]: but allowDefautFocus won't change once the dialog is mounted. So this useEffect will only (but reliably) run once when a dialog is mounted

Comment (WofWca) [reply packages/frontend/src/components/Dialog/Dialog.tsx:109]: Sure, the behavior is the same. It's just the semantics, future-proofing.
