### PR TITLE
Fix: Changing display name of a contact does not change it immediately in the messages

### LINKED ISSUE #3703: Editting name of a contact does not change their name in the messages
1. Rename some of your contacts by opening their profile, edit button.
2. See that their new name does not appear in the messages.
3. Select another chat and select the chat with the contact and see that the new name appears.

### PR DESCRIPTION
**Pull request by farooqkz**
Fix the bug where changing display name of a contact does not change it immediately in the messages

Closes #3703

### CODE REVIEW

File: src/renderer/components/message/Message.tsx [hunk 1]
```diff
@@ -88,7 +88,19 @@ const AuthorName = (
...
+  const update = async ({ contactId }: { contactId: number | null }) => {
+    if (contactId === id) {
+      const contact = await BackendRemote.rpc.getContact(
+        selectedAccountId(),
+        contactId
+      )
+      setDisplayName(contact.displayName)
+    }
+  }
+  onDCEvent(selectedAccountId(), 'ContactsChanged', update)
```
Comment (Simon-Laux) [inline src/renderer/components/message/Message.tsx:103]: you need to wrap this in useEffect, `onDCEvent` returns a cleanup function that unregisters the even listener, useEffect makes sure it is called.

See the other places where `onDCEvent` is used

**Review by Simon-Laux — CHANGES_REQUESTED** [review]

**Review by Simon-Laux — APPROVED** [review]
